// DO NOT EDIT. Auto-generated by tools/extract_linux_syscall_tables
#ifndef SRC_KERNEL_UTILS_SYSCALL_TABLE_GENERATED_H_
#define SRC_KERNEL_UTILS_SYSCALL_TABLE_GENERATED_H_

#include <stdint.h>

#include "src/kernel_utils/syscall_table.h"

namespace perfetto {

constexpr char kAllSyscalllNames[] =
    "\0"
    "sys__llseek\0"
    "sys__newselect\0"
    "sys__sysctl\0"
    "sys_accept\0"
    "sys_accept4\0"
    "sys_access\0"
    "sys_acct\0"
    "sys_add_key\0"
    "sys_adjtimex\0"
    "sys_afs_syscall\0"
    "sys_alarm\0"
    "sys_arch_prctl\0"
    "sys_arch_specific_syscall\0"
    "sys_arm_fadvise64_64\0"
    "sys_arm_sync_file_range\0"
    "sys_bdflush\0"
    "sys_bind\0"
    "sys_bpf\0"
    "sys_break\0"
    "sys_brk\0"
    "sys_cachestat\0"
    "sys_capget\0"
    "sys_capset\0"
    "sys_chdir\0"
    "sys_chmod\0"
    "sys_chown\0"
    "sys_chown32\0"
    "sys_chroot\0"
    "sys_clock_adjtime\0"
    "sys_clock_adjtime64\0"
    "sys_clock_getres\0"
    "sys_clock_getres_time64\0"
    "sys_clock_gettime\0"
    "sys_clock_gettime64\0"
    "sys_clock_nanosleep\0"
    "sys_clock_nanosleep_time64\0"
    "sys_clock_settime\0"
    "sys_clock_settime64\0"
    "sys_clone\0"
    "sys_clone3\0"
    "sys_close\0"
    "sys_close_range\0"
    "sys_connect\0"
    "sys_copy_file_range\0"
    "sys_creat\0"
    "sys_create_module\0"
    "sys_delete_module\0"
    "sys_dup\0"
    "sys_dup2\0"
    "sys_dup3\0"
    "sys_epoll_create\0"
    "sys_epoll_create1\0"
    "sys_epoll_ctl\0"
    "sys_epoll_ctl_old\0"
    "sys_epoll_pwait\0"
    "sys_epoll_pwait2\0"
    "sys_epoll_wait\0"
    "sys_epoll_wait_old\0"
    "sys_eventfd\0"
    "sys_eventfd2\0"
    "sys_execve\0"
    "sys_execveat\0"
    "sys_exit\0"
    "sys_exit_group\0"
    "sys_faccessat\0"
    "sys_faccessat2\0"
    "sys_fadvise64\0"
    "sys_fadvise64_64\0"
    "sys_fallocate\0"
    "sys_fanotify_init\0"
    "sys_fanotify_mark\0"
    "sys_fchdir\0"
    "sys_fchmod\0"
    "sys_fchmodat\0"
    "sys_fchmodat2\0"
    "sys_fchown\0"
    "sys_fchown32\0"
    "sys_fchownat\0"
    "sys_fcntl\0"
    "sys_fcntl64\0"
    "sys_fdatasync\0"
    "sys_fgetxattr\0"
    "sys_finit_module\0"
    "sys_flistxattr\0"
    "sys_flock\0"
    "sys_fork\0"
    "sys_fremovexattr\0"
    "sys_fsconfig\0"
    "sys_fsetxattr\0"
    "sys_fsmount\0"
    "sys_fsopen\0"
    "sys_fspick\0"
    "sys_fstat\0"
    "sys_fstat64\0"
    "sys_fstatat\0"
    "sys_fstatat64\0"
    "sys_fstatfs\0"
    "sys_fstatfs64\0"
    "sys_fsync\0"
    "sys_ftime\0"
    "sys_ftruncate\0"
    "sys_ftruncate64\0"
    "sys_futex\0"
    "sys_futex_requeue\0"
    "sys_futex_time64\0"
    "sys_futex_wait\0"
    "sys_futex_waitv\0"
    "sys_futex_wake\0"
    "sys_futimesat\0"
    "sys_get_kernel_syms\0"
    "sys_get_mempolicy\0"
    "sys_get_robust_list\0"
    "sys_get_thread_area\0"
    "sys_getcpu\0"
    "sys_getcwd\0"
    "sys_getdents\0"
    "sys_getdents64\0"
    "sys_getegid\0"
    "sys_getegid32\0"
    "sys_geteuid\0"
    "sys_geteuid32\0"
    "sys_getgid\0"
    "sys_getgid32\0"
    "sys_getgroups\0"
    "sys_getgroups32\0"
    "sys_getitimer\0"
    "sys_getpeername\0"
    "sys_getpgid\0"
    "sys_getpgrp\0"
    "sys_getpid\0"
    "sys_getpmsg\0"
    "sys_getppid\0"
    "sys_getpriority\0"
    "sys_getrandom\0"
    "sys_getresgid\0"
    "sys_getresgid32\0"
    "sys_getresuid\0"
    "sys_getresuid32\0"
    "sys_getrlimit\0"
    "sys_getrusage\0"
    "sys_getsid\0"
    "sys_getsockname\0"
    "sys_getsockopt\0"
    "sys_gettid\0"
    "sys_gettimeofday\0"
    "sys_getuid\0"
    "sys_getuid32\0"
    "sys_getxattr\0"
    "sys_gtty\0"
    "sys_idle\0"
    "sys_init_module\0"
    "sys_inotify_add_watch\0"
    "sys_inotify_init\0"
    "sys_inotify_init1\0"
    "sys_inotify_rm_watch\0"
    "sys_io_cancel\0"
    "sys_io_destroy\0"
    "sys_io_getevents\0"
    "sys_io_pgetevents\0"
    "sys_io_pgetevents_time64\0"
    "sys_io_setup\0"
    "sys_io_submit\0"
    "sys_io_uring_enter\0"
    "sys_io_uring_register\0"
    "sys_io_uring_setup\0"
    "sys_ioctl\0"
    "sys_ioperm\0"
    "sys_iopl\0"
    "sys_ioprio_get\0"
    "sys_ioprio_set\0"
    "sys_ipc\0"
    "sys_kcmp\0"
    "sys_kexec_file_load\0"
    "sys_kexec_load\0"
    "sys_keyctl\0"
    "sys_kill\0"
    "sys_landlock_add_rule\0"
    "sys_landlock_create_ruleset\0"
    "sys_landlock_restrict_self\0"
    "sys_lchown\0"
    "sys_lchown32\0"
    "sys_lgetxattr\0"
    "sys_link\0"
    "sys_linkat\0"
    "sys_listen\0"
    "sys_listxattr\0"
    "sys_llistxattr\0"
    "sys_lock\0"
    "sys_lookup_dcookie\0"
    "sys_lremovexattr\0"
    "sys_lseek\0"
    "sys_lsetxattr\0"
    "sys_lstat\0"
    "sys_lstat64\0"
    "sys_madvise\0"
    "sys_map_shadow_stack\0"
    "sys_mbind\0"
    "sys_membarrier\0"
    "sys_memfd_create\0"
    "sys_memfd_secret\0"
    "sys_migrate_pages\0"
    "sys_mincore\0"
    "sys_mkdir\0"
    "sys_mkdirat\0"
    "sys_mknod\0"
    "sys_mknodat\0"
    "sys_mlock\0"
    "sys_mlock2\0"
    "sys_mlockall\0"
    "sys_mmap\0"
    "sys_mmap2\0"
    "sys_modify_ldt\0"
    "sys_mount\0"
    "sys_mount_setattr\0"
    "sys_move_mount\0"
    "sys_move_pages\0"
    "sys_mprotect\0"
    "sys_mpx\0"
    "sys_mq_getsetattr\0"
    "sys_mq_notify\0"
    "sys_mq_open\0"
    "sys_mq_timedreceive\0"
    "sys_mq_timedreceive_time64\0"
    "sys_mq_timedsend\0"
    "sys_mq_timedsend_time64\0"
    "sys_mq_unlink\0"
    "sys_mremap\0"
    "sys_msgctl\0"
    "sys_msgget\0"
    "sys_msgrcv\0"
    "sys_msgsnd\0"
    "sys_msync\0"
    "sys_munlock\0"
    "sys_munlockall\0"
    "sys_munmap\0"
    "sys_name_to_handle_at\0"
    "sys_nanosleep\0"
    "sys_newfstatat\0"
    "sys_nfsservctl\0"
    "sys_nice\0"
    "sys_oldfstat\0"
    "sys_oldlstat\0"
    "sys_oldolduname\0"
    "sys_oldstat\0"
    "sys_olduname\0"
    "sys_open\0"
    "sys_open_by_handle_at\0"
    "sys_open_tree\0"
    "sys_openat\0"
    "sys_openat2\0"
    "sys_pause\0"
    "sys_pciconfig_iobase\0"
    "sys_pciconfig_read\0"
    "sys_pciconfig_write\0"
    "sys_perf_event_open\0"
    "sys_personality\0"
    "sys_pidfd_getfd\0"
    "sys_pidfd_open\0"
    "sys_pidfd_send_signal\0"
    "sys_pipe\0"
    "sys_pipe2\0"
    "sys_pivot_root\0"
    "sys_pkey_alloc\0"
    "sys_pkey_free\0"
    "sys_pkey_mprotect\0"
    "sys_poll\0"
    "sys_ppoll\0"
    "sys_ppoll_time64\0"
    "sys_prctl\0"
    "sys_pread64\0"
    "sys_preadv\0"
    "sys_preadv2\0"
    "sys_prlimit64\0"
    "sys_process_madvise\0"
    "sys_process_mrelease\0"
    "sys_process_vm_readv\0"
    "sys_process_vm_writev\0"
    "sys_prof\0"
    "sys_profil\0"
    "sys_pselect6\0"
    "sys_pselect6_time64\0"
    "sys_ptrace\0"
    "sys_putpmsg\0"
    "sys_pwrite64\0"
    "sys_pwritev\0"
    "sys_pwritev2\0"
    "sys_query_module\0"
    "sys_quotactl\0"
    "sys_quotactl_fd\0"
    "sys_read\0"
    "sys_readahead\0"
    "sys_readdir\0"
    "sys_readlink\0"
    "sys_readlinkat\0"
    "sys_readv\0"
    "sys_reboot\0"
    "sys_recv\0"
    "sys_recvfrom\0"
    "sys_recvmmsg\0"
    "sys_recvmmsg_time64\0"
    "sys_recvmsg\0"
    "sys_remap_file_pages\0"
    "sys_removexattr\0"
    "sys_rename\0"
    "sys_renameat\0"
    "sys_renameat2\0"
    "sys_request_key\0"
    "sys_restart_syscall\0"
    "sys_rmdir\0"
    "sys_rseq\0"
    "sys_rt_sigaction\0"
    "sys_rt_sigpending\0"
    "sys_rt_sigprocmask\0"
    "sys_rt_sigqueueinfo\0"
    "sys_rt_sigreturn\0"
    "sys_rt_sigsuspend\0"
    "sys_rt_sigtimedwait\0"
    "sys_rt_sigtimedwait_time64\0"
    "sys_rt_tgsigqueueinfo\0"
    "sys_s390_guarded_storage\0"
    "sys_s390_pci_mmio_read\0"
    "sys_s390_pci_mmio_write\0"
    "sys_s390_runtime_instr\0"
    "sys_s390_sthyi\0"
    "sys_sched_get_priority_max\0"
    "sys_sched_get_priority_min\0"
    "sys_sched_getaffinity\0"
    "sys_sched_getattr\0"
    "sys_sched_getparam\0"
    "sys_sched_getscheduler\0"
    "sys_sched_rr_get_interval\0"
    "sys_sched_rr_get_interval_time64\0"
    "sys_sched_setaffinity\0"
    "sys_sched_setattr\0"
    "sys_sched_setparam\0"
    "sys_sched_setscheduler\0"
    "sys_sched_yield\0"
    "sys_seccomp\0"
    "sys_security\0"
    "sys_select\0"
    "sys_semctl\0"
    "sys_semget\0"
    "sys_semop\0"
    "sys_semtimedop\0"
    "sys_semtimedop_time64\0"
    "sys_send\0"
    "sys_sendfile\0"
    "sys_sendfile64\0"
    "sys_sendmmsg\0"
    "sys_sendmsg\0"
    "sys_sendto\0"
    "sys_set_mempolicy\0"
    "sys_set_mempolicy_home_node\0"
    "sys_set_robust_list\0"
    "sys_set_thread_area\0"
    "sys_set_tid_address\0"
    "sys_setdomainname\0"
    "sys_setfsgid\0"
    "sys_setfsgid32\0"
    "sys_setfsuid\0"
    "sys_setfsuid32\0"
    "sys_setgid\0"
    "sys_setgid32\0"
    "sys_setgroups\0"
    "sys_setgroups32\0"
    "sys_sethostname\0"
    "sys_setitimer\0"
    "sys_setns\0"
    "sys_setpgid\0"
    "sys_setpriority\0"
    "sys_setregid\0"
    "sys_setregid32\0"
    "sys_setresgid\0"
    "sys_setresgid32\0"
    "sys_setresuid\0"
    "sys_setresuid32\0"
    "sys_setreuid\0"
    "sys_setreuid32\0"
    "sys_setrlimit\0"
    "sys_setsid\0"
    "sys_setsockopt\0"
    "sys_settimeofday\0"
    "sys_setuid\0"
    "sys_setuid32\0"
    "sys_setxattr\0"
    "sys_sgetmask\0"
    "sys_shmat\0"
    "sys_shmctl\0"
    "sys_shmdt\0"
    "sys_shmget\0"
    "sys_shutdown\0"
    "sys_sigaction\0"
    "sys_sigaltstack\0"
    "sys_signal\0"
    "sys_signalfd\0"
    "sys_signalfd4\0"
    "sys_sigpending\0"
    "sys_sigprocmask\0"
    "sys_sigreturn\0"
    "sys_sigsuspend\0"
    "sys_socket\0"
    "sys_socketcall\0"
    "sys_socketpair\0"
    "sys_splice\0"
    "sys_ssetmask\0"
    "sys_stat\0"
    "sys_stat64\0"
    "sys_statfs\0"
    "sys_statfs64\0"
    "sys_statx\0"
    "sys_stime\0"
    "sys_stty\0"
    "sys_swapoff\0"
    "sys_swapon\0"
    "sys_symlink\0"
    "sys_symlinkat\0"
    "sys_sync\0"
    "sys_sync_file_range\0"
    "sys_syncfs\0"
    "sys_syscall\0"
    "sys_sysfs\0"
    "sys_sysinfo\0"
    "sys_syslog\0"
    "sys_tee\0"
    "sys_tgkill\0"
    "sys_time\0"
    "sys_timer_create\0"
    "sys_timer_delete\0"
    "sys_timer_getoverrun\0"
    "sys_timer_gettime\0"
    "sys_timer_gettime64\0"
    "sys_timer_settime\0"
    "sys_timer_settime64\0"
    "sys_timerfd\0"
    "sys_timerfd_create\0"
    "sys_timerfd_gettime\0"
    "sys_timerfd_gettime64\0"
    "sys_timerfd_settime\0"
    "sys_timerfd_settime64\0"
    "sys_times\0"
    "sys_tkill\0"
    "sys_truncate\0"
    "sys_truncate64\0"
    "sys_tuxcall\0"
    "sys_ugetrlimit\0"
    "sys_ulimit\0"
    "sys_umask\0"
    "sys_umount\0"
    "sys_umount2\0"
    "sys_uname\0"
    "sys_unlink\0"
    "sys_unlinkat\0"
    "sys_unshare\0"
    "sys_uselib\0"
    "sys_userfaultfd\0"
    "sys_ustat\0"
    "sys_utime\0"
    "sys_utimensat\0"
    "sys_utimensat_time64\0"
    "sys_utimes\0"
    "sys_vfork\0"
    "sys_vhangup\0"
    "sys_vm86\0"
    "sys_vm86old\0"
    "sys_vmsplice\0"
    "sys_vserver\0"
    "sys_wait4\0"
    "sys_waitid\0"
    "sys_waitpid\0"
    "sys_write\0"
    "sys_writev\0";

struct SyscallTable_arm64 {
  static constexpr const char* names = kAllSyscalllNames;
  static constexpr SyscallTable::OffT offsets[]{
      2269,  // 0: sys_io_setup
      2194,  // 1: sys_io_destroy
      2282,  // 2: sys_io_submit
      2180,  // 3: sys_io_cancel
      2209,  // 4: sys_io_getevents
      5644,  // 5: sys_setxattr
      2718,  // 6: sys_lsetxattr
      1243,  // 7: sys_fsetxattr
      2055,  // 8: sys_getxattr
      2589,  // 9: sys_lgetxattr
      1148,  // 10: sys_fgetxattr
      2634,  // 11: sys_listxattr
      2648,  // 12: sys_llistxattr
      1179,  // 13: sys_flistxattr
      4277,  // 14: sys_removexattr
      2691,  // 15: sys_lremovexattr
      1213,  // 16: sys_fremovexattr
      1609,  // 17: sys_getcwd
      2672,  // 18: sys_lookup_dcookie
      855,   // 19: sys_eventfd2
      726,   // 20: sys_epoll_create1
      744,   // 21: sys_epoll_ctl
      776,   // 22: sys_epoll_pwait
      683,   // 23: sys_dup
      700,   // 24: sys_dup3
      1112,  // 25: sys_fcntl
      2141,  // 26: sys_inotify_init1
      2102,  // 27: sys_inotify_add_watch
      2159,  // 28: sys_inotify_rm_watch
      2356,  // 29: sys_ioctl
      2401,  // 30: sys_ioprio_set
      2386,  // 31: sys_ioprio_get
      1194,  // 32: sys_flock
      2908,  // 33: sys_mknodat
      2886,  // 34: sys_mkdirat
      6539,  // 35: sys_unlinkat
      6026,  // 36: sys_symlinkat
      2612,  // 37: sys_linkat
      4304,  // 38: sys_renameat
      6506,  // 39: sys_umount2
      2988,  // 40: sys_mount
      3704,  // 41: sys_pivot_root
      3367,  // 42: sys_nfsservctl
      5938,  // 43: sys_statfs
      1339,  // 44: sys_fstatfs
      6419,  // 45: sys_truncate
      1385,  // 46: sys_ftruncate
      976,   // 47: sys_fallocate
      916,   // 48: sys_faccessat
      303,   // 49: sys_chdir
      1026,  // 50: sys_fchdir
      345,   // 51: sys_chroot
      1037,  // 52: sys_fchmod
      1048,  // 53: sys_fchmodat
      1099,  // 54: sys_fchownat
      1075,  // 55: sys_fchown
      3503,  // 56: sys_openat
      579,   // 57: sys_close
      6667,  // 58: sys_vhangup
      3694,  // 59: sys_pipe2
      4076,  // 60: sys_quotactl
      1633,  // 61: sys_getdents64
      2708,  // 62: sys_lseek
      4105,  // 63: sys_read
      6758,  // 64: sys_write
      4168,  // 65: sys_readv
      6768,  // 66: sys_writev
      3812,  // 67: sys_pread64
      4021,  // 68: sys_pwrite64
      3824,  // 69: sys_preadv
      4034,  // 70: sys_pwritev
      5081,  // 71: sys_sendfile
      3965,  // 72: sys_pselect6
      3775,  // 73: sys_ppoll
      5779,  // 74: sys_signalfd4
      6700,  // 75: sys_vmsplice
      5894,  // 76: sys_splice
      6125,  // 77: sys_tee
      4153,  // 78: sys_readlinkat
      1313,  // 79: sys_fstatat
      1291,  // 80: sys_fstat
      6040,  // 81: sys_sync
      1365,  // 82: sys_fsync
      1134,  // 83: sys_fdatasync
      6049,  // 84: sys_sync_file_range
      6296,  // 85: sys_timerfd_create
      6357,  // 86: sys_timerfd_settime
      6315,  // 87: sys_timerfd_gettime
      6611,  // 88: sys_utimensat
      74,    // 89: sys_acct
      281,   // 90: sys_capget
      292,   // 91: sys_capset
      3616,  // 92: sys_personality
      892,   // 93: sys_exit
      901,   // 94: sys_exit_group
      6735,  // 95: sys_waitid
      5231,  // 96: sys_set_tid_address
      6552,  // 97: sys_unshare
      1415,  // 98: sys_futex
      5191,  // 99: sys_set_robust_list
      1558,  // 100: sys_get_robust_list
      3338,  // 101: sys_nanosleep
      1754,  // 102: sys_getitimer
      5395,  // 103: sys_setitimer
      2453,  // 104: sys_kexec_load
      2086,  // 105: sys_init_module
      665,   // 106: sys_delete_module
      6153,  // 107: sys_timer_create
      6208,  // 108: sys_timer_gettime
      6187,  // 109: sys_timer_getoverrun
      6246,  // 110: sys_timer_settime
      6170,  // 111: sys_timer_delete
      520,   // 112: sys_clock_settime
      435,   // 113: sys_clock_gettime
      394,   // 114: sys_clock_getres
      473,   // 115: sys_clock_nanosleep
      6114,  // 116: sys_syslog
      3998,  // 117: sys_ptrace
      4909,  // 118: sys_sched_setparam
      4928,  // 119: sys_sched_setscheduler
      4787,  // 120: sys_sched_getscheduler
      4768,  // 121: sys_sched_getparam
      4869,  // 122: sys_sched_setaffinity
      4728,  // 123: sys_sched_getaffinity
      4951,  // 124: sys_sched_yield
      4674,  // 125: sys_sched_get_priority_max
      4701,  // 126: sys_sched_get_priority_min
      4810,  // 127: sys_sched_rr_get_interval
      4347,  // 128: sys_restart_syscall
      2479,  // 129: sys_kill
      6409,  // 130: sys_tkill
      6133,  // 131: sys_tgkill
      5739,  // 132: sys_sigaltstack
      4477,  // 133: sys_rt_sigsuspend
      4386,  // 134: sys_rt_sigaction
      4421,  // 135: sys_rt_sigprocmask
      4403,  // 136: sys_rt_sigpending
      4495,  // 137: sys_rt_sigtimedwait
      4440,  // 138: sys_rt_sigqueueinfo
      4460,  // 139: sys_rt_sigreturn
      5431,  // 140: sys_setpriority
      1843,  // 141: sys_getpriority
      4178,  // 142: sys_reboot
      5447,  // 143: sys_setregid
      5325,  // 144: sys_setgid
      5535,  // 145: sys_setreuid
      5620,  // 146: sys_setuid
      5505,  // 147: sys_setresuid
      1903,  // 148: sys_getresuid
      5475,  // 149: sys_setresgid
      1873,  // 150: sys_getresgid
      5297,  // 151: sys_setfsuid
      5269,  // 152: sys_setfsgid
      6399,  // 153: sys_times
      5419,  // 154: sys_setpgid
      1784,  // 155: sys_getpgid
      1961,  // 156: sys_getsid
      5577,  // 157: sys_setsid
      1724,  // 158: sys_getgroups
      5349,  // 159: sys_setgroups
      6518,  // 160: sys_uname
      5379,  // 161: sys_sethostname
      5251,  // 162: sys_setdomainname
      1933,  // 163: sys_getrlimit
      5563,  // 164: sys_setrlimit
      1947,  // 165: sys_getrusage
      6485,  // 166: sys_umask
      3802,  // 167: sys_prctl
      1598,  // 168: sys_getcpu
      2014,  // 169: sys_gettimeofday
      5603,  // 170: sys_settimeofday
      95,    // 171: sys_adjtimex
      1808,  // 172: sys_getpid
      1831,  // 173: sys_getppid
      2031,  // 174: sys_getuid
      1674,  // 175: sys_geteuid
      1700,  // 176: sys_getgid
      1648,  // 177: sys_getegid
      2003,  // 178: sys_gettid
      6102,  // 179: sys_sysinfo
      3099,  // 180: sys_mq_open
      3199,  // 181: sys_mq_unlink
      3158,  // 182: sys_mq_timedsend
      3111,  // 183: sys_mq_timedreceive
      3085,  // 184: sys_mq_notify
      3067,  // 185: sys_mq_getsetattr
      3235,  // 186: sys_msgget
      3224,  // 187: sys_msgctl
      3246,  // 188: sys_msgrcv
      3257,  // 189: sys_msgsnd
      5014,  // 190: sys_semget
      5003,  // 191: sys_semctl
      5035,  // 192: sys_semtimedop
      5025,  // 193: sys_semop
      5701,  // 194: sys_shmget
      5680,  // 195: sys_shmctl
      5670,  // 196: sys_shmat
      5691,  // 197: sys_shmdt
      5853,  // 198: sys_socket
      5879,  // 199: sys_socketpair
      232,   // 200: sys_bind
      2623,  // 201: sys_listen
      40,    // 202: sys_accept
      605,   // 203: sys_connect
      1972,  // 204: sys_getsockname
      1768,  // 205: sys_getpeername
      5134,  // 206: sys_sendto
      4198,  // 207: sys_recvfrom
      5588,  // 208: sys_setsockopt
      1988,  // 209: sys_getsockopt
      5712,  // 210: sys_shutdown
      5122,  // 211: sys_sendmsg
      4244,  // 212: sys_recvmsg
      4114,  // 213: sys_readahead
      259,   // 214: sys_brk
      3305,  // 215: sys_munmap
      3213,  // 216: sys_mremap
      83,    // 217: sys_add_key
      4331,  // 218: sys_request_key
      2468,  // 219: sys_keyctl
      558,   // 220: sys_clone
      868,   // 221: sys_execve
      2954,  // 222: sys_mmap
      945,   // 223: sys_fadvise64
      6003,  // 224: sys_swapon
      5991,  // 225: sys_swapoff
      3046,  // 226: sys_mprotect
      3268,  // 227: sys_msync
      2920,  // 228: sys_mlock
      3278,  // 229: sys_munlock
      2941,  // 230: sys_mlockall
      3290,  // 231: sys_munlockall
      2864,  // 232: sys_mincore
      2754,  // 233: sys_madvise
      4256,  // 234: sys_remap_file_pages
      2787,  // 235: sys_mbind
      1540,  // 236: sys_get_mempolicy
      5145,  // 237: sys_set_mempolicy
      2846,  // 238: sys_migrate_pages
      3031,  // 239: sys_move_pages
      4542,  // 240: sys_rt_tgsigqueueinfo
      3596,  // 241: sys_perf_event_open
      51,    // 242: sys_accept4
      4211,  // 243: sys_recvmmsg
      149,   // 244: sys_arch_specific_syscall
      0,     // 245:
      0,     // 246:
      0,     // 247:
      0,     // 248:
      0,     // 249:
      0,     // 250:
      0,     // 251:
      0,     // 252:
      0,     // 253:
      0,     // 254:
      0,     // 255:
      0,     // 256:
      0,     // 257:
      0,     // 258:
      0,     // 259:
      6725,  // 260: sys_wait4
      3847,  // 261: sys_prlimit64
      990,   // 262: sys_fanotify_init
      1008,  // 263: sys_fanotify_mark
      3316,  // 264: sys_name_to_handle_at
      3467,  // 265: sys_open_by_handle_at
      356,   // 266: sys_clock_adjtime
      6069,  // 267: sys_syncfs
      5409,  // 268: sys_setns
      5109,  // 269: sys_sendmmsg
      3902,  // 270: sys_process_vm_readv
      3923,  // 271: sys_process_vm_writev
      2424,  // 272: sys_kcmp
      1162,  // 273: sys_finit_module
      4891,  // 274: sys_sched_setattr
      4750,  // 275: sys_sched_getattr
      4317,  // 276: sys_renameat2
      4967,  // 277: sys_seccomp
      1859,  // 278: sys_getrandom
      2812,  // 279: sys_memfd_create
      241,   // 280: sys_bpf
      879,   // 281: sys_execveat
      6575,  // 282: sys_userfaultfd
      2797,  // 283: sys_membarrier
      2930,  // 284: sys_mlock2
      617,   // 285: sys_copy_file_range
      3835,  // 286: sys_preadv2
      4046,  // 287: sys_pwritev2
      3748,  // 288: sys_pkey_mprotect
      3719,  // 289: sys_pkey_alloc
      3734,  // 290: sys_pkey_free
      5962,  // 291: sys_statx
      2226,  // 292: sys_io_pgetevents
      4377,  // 293: sys_rseq
      2433,  // 294: sys_kexec_file_load
      0,     // 295:
      0,     // 296:
      0,     // 297:
      0,     // 298:
      0,     // 299:
      0,     // 300:
      0,     // 301:
      0,     // 302:
      0,     // 303:
      0,     // 304:
      0,     // 305:
      0,     // 306:
      0,     // 307:
      0,     // 308:
      0,     // 309:
      0,     // 310:
      0,     // 311:
      0,     // 312:
      0,     // 313:
      0,     // 314:
      0,     // 315:
      0,     // 316:
      0,     // 317:
      0,     // 318:
      0,     // 319:
      0,     // 320:
      0,     // 321:
      0,     // 322:
      0,     // 323:
      0,     // 324:
      0,     // 325:
      0,     // 326:
      0,     // 327:
      0,     // 328:
      0,     // 329:
      0,     // 330:
      0,     // 331:
      0,     // 332:
      0,     // 333:
      0,     // 334:
      0,     // 335:
      0,     // 336:
      0,     // 337:
      0,     // 338:
      0,     // 339:
      0,     // 340:
      0,     // 341:
      0,     // 342:
      0,     // 343:
      0,     // 344:
      0,     // 345:
      0,     // 346:
      0,     // 347:
      0,     // 348:
      0,     // 349:
      0,     // 350:
      0,     // 351:
      0,     // 352:
      0,     // 353:
      0,     // 354:
      0,     // 355:
      0,     // 356:
      0,     // 357:
      0,     // 358:
      0,     // 359:
      0,     // 360:
      0,     // 361:
      0,     // 362:
      0,     // 363:
      0,     // 364:
      0,     // 365:
      0,     // 366:
      0,     // 367:
      0,     // 368:
      0,     // 369:
      0,     // 370:
      0,     // 371:
      0,     // 372:
      0,     // 373:
      0,     // 374:
      0,     // 375:
      0,     // 376:
      0,     // 377:
      0,     // 378:
      0,     // 379:
      0,     // 380:
      0,     // 381:
      0,     // 382:
      0,     // 383:
      0,     // 384:
      0,     // 385:
      0,     // 386:
      0,     // 387:
      0,     // 388:
      0,     // 389:
      0,     // 390:
      0,     // 391:
      0,     // 392:
      0,     // 393:
      0,     // 394:
      0,     // 395:
      0,     // 396:
      0,     // 397:
      0,     // 398:
      0,     // 399:
      0,     // 400:
      0,     // 401:
      0,     // 402:
      453,   // 403: sys_clock_gettime64
      538,   // 404: sys_clock_settime64
      374,   // 405: sys_clock_adjtime64
      411,   // 406: sys_clock_getres_time64
      493,   // 407: sys_clock_nanosleep_time64
      6226,  // 408: sys_timer_gettime64
      6264,  // 409: sys_timer_settime64
      6335,  // 410: sys_timerfd_gettime64
      6377,  // 411: sys_timerfd_settime64
      6625,  // 412: sys_utimensat_time64
      3978,  // 413: sys_pselect6_time64
      3785,  // 414: sys_ppoll_time64
      0,     // 415:
      2244,  // 416: sys_io_pgetevents_time64
      4224,  // 417: sys_recvmmsg_time64
      3175,  // 418: sys_mq_timedsend_time64
      3131,  // 419: sys_mq_timedreceive_time64
      5050,  // 420: sys_semtimedop_time64
      4515,  // 421: sys_rt_sigtimedwait_time64
      1443,  // 422: sys_futex_time64
      4836,  // 423: sys_sched_rr_get_interval_time64
      3663,  // 424: sys_pidfd_send_signal
      2337,  // 425: sys_io_uring_setup
      2296,  // 426: sys_io_uring_enter
      2315,  // 427: sys_io_uring_register
      3489,  // 428: sys_open_tree
      3016,  // 429: sys_move_mount
      1269,  // 430: sys_fsopen
      1230,  // 431: sys_fsconfig
      1257,  // 432: sys_fsmount
      1280,  // 433: sys_fspick
      3648,  // 434: sys_pidfd_open
      568,   // 435: sys_clone3
      589,   // 436: sys_close_range
      3514,  // 437: sys_openat2
      3632,  // 438: sys_pidfd_getfd
      930,   // 439: sys_faccessat2
      3861,  // 440: sys_process_madvise
      792,   // 441: sys_epoll_pwait2
      2998,  // 442: sys_mount_setattr
      4089,  // 443: sys_quotactl_fd
      2510,  // 444: sys_landlock_create_ruleset
      2488,  // 445: sys_landlock_add_rule
      2538,  // 446: sys_landlock_restrict_self
      2829,  // 447: sys_memfd_secret
      3881,  // 448: sys_process_mrelease
      1475,  // 449: sys_futex_waitv
      5163,  // 450: sys_set_mempolicy_home_node
      267,   // 451: sys_cachestat
      1061,  // 452: sys_fchmodat2
      2766,  // 453: sys_map_shadow_stack
      1491,  // 454: sys_futex_wake
      1460,  // 455: sys_futex_wait
      1425,  // 456: sys_futex_requeue
  };
};

struct SyscallTable_arm32 {
  static constexpr const char* names = kAllSyscalllNames;
  static constexpr SyscallTable::OffT offsets[]{
      4347,  // 0: sys_restart_syscall
      892,   // 1: sys_exit
      1204,  // 2: sys_fork
      4105,  // 3: sys_read
      6758,  // 4: sys_write
      3458,  // 5: sys_open
      579,   // 6: sys_close
      0,     // 7:
      637,   // 8: sys_creat
      2603,  // 9: sys_link
      6528,  // 10: sys_unlink
      868,   // 11: sys_execve
      303,   // 12: sys_chdir
      6144,  // 13: sys_time
      2898,  // 14: sys_mknod
      313,   // 15: sys_chmod
      2565,  // 16: sys_lchown
      0,     // 17:
      0,     // 18:
      2708,  // 19: sys_lseek
      1808,  // 20: sys_getpid
      2988,  // 21: sys_mount
      6495,  // 22: sys_umount
      5620,  // 23: sys_setuid
      2031,  // 24: sys_getuid
      5972,  // 25: sys_stime
      3998,  // 26: sys_ptrace
      124,   // 27: sys_alarm
      0,     // 28:
      3526,  // 29: sys_pause
      6601,  // 30: sys_utime
      0,     // 31:
      0,     // 32:
      63,    // 33: sys_access
      3382,  // 34: sys_nice
      0,     // 35:
      6040,  // 36: sys_sync
      2479,  // 37: sys_kill
      4293,  // 38: sys_rename
      2876,  // 39: sys_mkdir
      4367,  // 40: sys_rmdir
      683,   // 41: sys_dup
      3685,  // 42: sys_pipe
      6399,  // 43: sys_times
      0,     // 44:
      259,   // 45: sys_brk
      5325,  // 46: sys_setgid
      1700,  // 47: sys_getgid
      0,     // 48:
      1674,  // 49: sys_geteuid
      1648,  // 50: sys_getegid
      74,    // 51: sys_acct
      6506,  // 52: sys_umount2
      0,     // 53:
      2356,  // 54: sys_ioctl
      1112,  // 55: sys_fcntl
      0,     // 56:
      5419,  // 57: sys_setpgid
      0,     // 58:
      0,     // 59:
      6485,  // 60: sys_umask
      345,   // 61: sys_chroot
      6591,  // 62: sys_ustat
      691,   // 63: sys_dup2
      1831,  // 64: sys_getppid
      1796,  // 65: sys_getpgrp
      5577,  // 66: sys_setsid
      5725,  // 67: sys_sigaction
      0,     // 68:
      0,     // 69:
      5535,  // 70: sys_setreuid
      5447,  // 71: sys_setregid
      5838,  // 72: sys_sigsuspend
      5793,  // 73: sys_sigpending
      5379,  // 74: sys_sethostname
      5563,  // 75: sys_setrlimit
      1933,  // 76: sys_getrlimit
      1947,  // 77: sys_getrusage
      2014,  // 78: sys_gettimeofday
      5603,  // 79: sys_settimeofday
      1724,  // 80: sys_getgroups
      5349,  // 81: sys_setgroups
      4992,  // 82: sys_select
      6014,  // 83: sys_symlink
      0,     // 84:
      4140,  // 85: sys_readlink
      6564,  // 86: sys_uselib
      6003,  // 87: sys_swapon
      4178,  // 88: sys_reboot
      4128,  // 89: sys_readdir
      2954,  // 90: sys_mmap
      3305,  // 91: sys_munmap
      6419,  // 92: sys_truncate
      1385,  // 93: sys_ftruncate
      1037,  // 94: sys_fchmod
      1075,  // 95: sys_fchown
      1843,  // 96: sys_getpriority
      5431,  // 97: sys_setpriority
      0,     // 98:
      5938,  // 99: sys_statfs
      1339,  // 100: sys_fstatfs
      0,     // 101:
      5864,  // 102: sys_socketcall
      6114,  // 103: sys_syslog
      5395,  // 104: sys_setitimer
      1754,  // 105: sys_getitimer
      5918,  // 106: sys_stat
      2732,  // 107: sys_lstat
      1291,  // 108: sys_fstat
      0,     // 109:
      0,     // 110:
      6667,  // 111: sys_vhangup
      0,     // 112:
      6080,  // 113: sys_syscall
      6725,  // 114: sys_wait4
      5991,  // 115: sys_swapoff
      6102,  // 116: sys_sysinfo
      2416,  // 117: sys_ipc
      1365,  // 118: sys_fsync
      5824,  // 119: sys_sigreturn
      558,   // 120: sys_clone
      5251,  // 121: sys_setdomainname
      6518,  // 122: sys_uname
      0,     // 123:
      95,    // 124: sys_adjtimex
      3046,  // 125: sys_mprotect
      5808,  // 126: sys_sigprocmask
      0,     // 127:
      2086,  // 128: sys_init_module
      665,   // 129: sys_delete_module
      0,     // 130:
      4076,  // 131: sys_quotactl
      1784,  // 132: sys_getpgid
      1026,  // 133: sys_fchdir
      220,   // 134: sys_bdflush
      6092,  // 135: sys_sysfs
      3616,  // 136: sys_personality
      0,     // 137:
      5297,  // 138: sys_setfsuid
      5269,  // 139: sys_setfsgid
      1,     // 140: sys__llseek
      1620,  // 141: sys_getdents
      13,    // 142: sys__newselect
      1194,  // 143: sys_flock
      3268,  // 144: sys_msync
      4168,  // 145: sys_readv
      6768,  // 146: sys_writev
      1961,  // 147: sys_getsid
      1134,  // 148: sys_fdatasync
      28,    // 149: sys__sysctl
      2920,  // 150: sys_mlock
      3278,  // 151: sys_munlock
      2941,  // 152: sys_mlockall
      3290,  // 153: sys_munlockall
      4909,  // 154: sys_sched_setparam
      4768,  // 155: sys_sched_getparam
      4928,  // 156: sys_sched_setscheduler
      4787,  // 157: sys_sched_getscheduler
      4951,  // 158: sys_sched_yield
      4674,  // 159: sys_sched_get_priority_max
      4701,  // 160: sys_sched_get_priority_min
      4810,  // 161: sys_sched_rr_get_interval
      3338,  // 162: sys_nanosleep
      3213,  // 163: sys_mremap
      5505,  // 164: sys_setresuid
      1903,  // 165: sys_getresuid
      0,     // 166:
      0,     // 167:
      3766,  // 168: sys_poll
      3367,  // 169: sys_nfsservctl
      5475,  // 170: sys_setresgid
      1873,  // 171: sys_getresgid
      3802,  // 172: sys_prctl
      4460,  // 173: sys_rt_sigreturn
      4386,  // 174: sys_rt_sigaction
      4421,  // 175: sys_rt_sigprocmask
      4403,  // 176: sys_rt_sigpending
      4495,  // 177: sys_rt_sigtimedwait
      4440,  // 178: sys_rt_sigqueueinfo
      4477,  // 179: sys_rt_sigsuspend
      3812,  // 180: sys_pread64
      4021,  // 181: sys_pwrite64
      323,   // 182: sys_chown
      1609,  // 183: sys_getcwd
      281,   // 184: sys_capget
      292,   // 185: sys_capset
      5739,  // 186: sys_sigaltstack
      5081,  // 187: sys_sendfile
      0,     // 188:
      0,     // 189:
      6657,  // 190: sys_vfork
      6459,  // 191: sys_ugetrlimit
      2963,  // 192: sys_mmap2
      6432,  // 193: sys_truncate64
      1399,  // 194: sys_ftruncate64
      5927,  // 195: sys_stat64
      2742,  // 196: sys_lstat64
      1301,  // 197: sys_fstat64
      2576,  // 198: sys_lchown32
      2042,  // 199: sys_getuid32
      1711,  // 200: sys_getgid32
      1686,  // 201: sys_geteuid32
      1660,  // 202: sys_getegid32
      5548,  // 203: sys_setreuid32
      5460,  // 204: sys_setregid32
      1738,  // 205: sys_getgroups32
      5363,  // 206: sys_setgroups32
      1086,  // 207: sys_fchown32
      5519,  // 208: sys_setresuid32
      1917,  // 209: sys_getresuid32
      5489,  // 210: sys_setresgid32
      1887,  // 211: sys_getresgid32
      333,   // 212: sys_chown32
      5631,  // 213: sys_setuid32
      5336,  // 214: sys_setgid32
      5310,  // 215: sys_setfsuid32
      5282,  // 216: sys_setfsgid32
      1633,  // 217: sys_getdents64
      3704,  // 218: sys_pivot_root
      2864,  // 219: sys_mincore
      2754,  // 220: sys_madvise
      1122,  // 221: sys_fcntl64
      0,     // 222:
      0,     // 223:
      2003,  // 224: sys_gettid
      4114,  // 225: sys_readahead
      5644,  // 226: sys_setxattr
      2718,  // 227: sys_lsetxattr
      1243,  // 228: sys_fsetxattr
      2055,  // 229: sys_getxattr
      2589,  // 230: sys_lgetxattr
      1148,  // 231: sys_fgetxattr
      2634,  // 232: sys_listxattr
      2648,  // 233: sys_llistxattr
      1179,  // 234: sys_flistxattr
      4277,  // 235: sys_removexattr
      2691,  // 236: sys_lremovexattr
      1213,  // 237: sys_fremovexattr
      6409,  // 238: sys_tkill
      5094,  // 239: sys_sendfile64
      1415,  // 240: sys_futex
      4869,  // 241: sys_sched_setaffinity
      4728,  // 242: sys_sched_getaffinity
      2269,  // 243: sys_io_setup
      2194,  // 244: sys_io_destroy
      2209,  // 245: sys_io_getevents
      2282,  // 246: sys_io_submit
      2180,  // 247: sys_io_cancel
      901,   // 248: sys_exit_group
      2672,  // 249: sys_lookup_dcookie
      709,   // 250: sys_epoll_create
      744,   // 251: sys_epoll_ctl
      809,   // 252: sys_epoll_wait
      4256,  // 253: sys_remap_file_pages
      0,     // 254:
      0,     // 255:
      5231,  // 256: sys_set_tid_address
      6153,  // 257: sys_timer_create
      6246,  // 258: sys_timer_settime
      6208,  // 259: sys_timer_gettime
      6187,  // 260: sys_timer_getoverrun
      6170,  // 261: sys_timer_delete
      520,   // 262: sys_clock_settime
      435,   // 263: sys_clock_gettime
      394,   // 264: sys_clock_getres
      473,   // 265: sys_clock_nanosleep
      5949,  // 266: sys_statfs64
      1351,  // 267: sys_fstatfs64
      6133,  // 268: sys_tgkill
      6646,  // 269: sys_utimes
      175,   // 270: sys_arm_fadvise64_64
      3536,  // 271: sys_pciconfig_iobase
      3557,  // 272: sys_pciconfig_read
      3576,  // 273: sys_pciconfig_write
      3099,  // 274: sys_mq_open
      3199,  // 275: sys_mq_unlink
      3158,  // 276: sys_mq_timedsend
      3111,  // 277: sys_mq_timedreceive
      3085,  // 278: sys_mq_notify
      3067,  // 279: sys_mq_getsetattr
      6735,  // 280: sys_waitid
      5853,  // 281: sys_socket
      232,   // 282: sys_bind
      605,   // 283: sys_connect
      2623,  // 284: sys_listen
      40,    // 285: sys_accept
      1972,  // 286: sys_getsockname
      1768,  // 287: sys_getpeername
      5879,  // 288: sys_socketpair
      5072,  // 289: sys_send
      5134,  // 290: sys_sendto
      4189,  // 291: sys_recv
      4198,  // 292: sys_recvfrom
      5712,  // 293: sys_shutdown
      5588,  // 294: sys_setsockopt
      1988,  // 295: sys_getsockopt
      5122,  // 296: sys_sendmsg
      4244,  // 297: sys_recvmsg
      5025,  // 298: sys_semop
      5014,  // 299: sys_semget
      5003,  // 300: sys_semctl
      3257,  // 301: sys_msgsnd
      3246,  // 302: sys_msgrcv
      3235,  // 303: sys_msgget
      3224,  // 304: sys_msgctl
      5670,  // 305: sys_shmat
      5691,  // 306: sys_shmdt
      5701,  // 307: sys_shmget
      5680,  // 308: sys_shmctl
      83,    // 309: sys_add_key
      4331,  // 310: sys_request_key
      2468,  // 311: sys_keyctl
      5035,  // 312: sys_semtimedop
      6713,  // 313: sys_vserver
      2401,  // 314: sys_ioprio_set
      2386,  // 315: sys_ioprio_get
      2124,  // 316: sys_inotify_init
      2102,  // 317: sys_inotify_add_watch
      2159,  // 318: sys_inotify_rm_watch
      2787,  // 319: sys_mbind
      1540,  // 320: sys_get_mempolicy
      5145,  // 321: sys_set_mempolicy
      3503,  // 322: sys_openat
      2886,  // 323: sys_mkdirat
      2908,  // 324: sys_mknodat
      1099,  // 325: sys_fchownat
      1506,  // 326: sys_futimesat
      1325,  // 327: sys_fstatat64
      6539,  // 328: sys_unlinkat
      4304,  // 329: sys_renameat
      2612,  // 330: sys_linkat
      6026,  // 331: sys_symlinkat
      4153,  // 332: sys_readlinkat
      1048,  // 333: sys_fchmodat
      916,   // 334: sys_faccessat
      3965,  // 335: sys_pselect6
      3775,  // 336: sys_ppoll
      6552,  // 337: sys_unshare
      5191,  // 338: sys_set_robust_list
      1558,  // 339: sys_get_robust_list
      5894,  // 340: sys_splice
      196,   // 341: sys_arm_sync_file_range
      6125,  // 342: sys_tee
      6700,  // 343: sys_vmsplice
      3031,  // 344: sys_move_pages
      1598,  // 345: sys_getcpu
      776,   // 346: sys_epoll_pwait
      2453,  // 347: sys_kexec_load
      6611,  // 348: sys_utimensat
      5766,  // 349: sys_signalfd
      6296,  // 350: sys_timerfd_create
      843,   // 351: sys_eventfd
      976,   // 352: sys_fallocate
      6357,  // 353: sys_timerfd_settime
      6315,  // 354: sys_timerfd_gettime
      5779,  // 355: sys_signalfd4
      855,   // 356: sys_eventfd2
      726,   // 357: sys_epoll_create1
      700,   // 358: sys_dup3
      3694,  // 359: sys_pipe2
      2141,  // 360: sys_inotify_init1
      3824,  // 361: sys_preadv
      4034,  // 362: sys_pwritev
      4542,  // 363: sys_rt_tgsigqueueinfo
      3596,  // 364: sys_perf_event_open
      4211,  // 365: sys_recvmmsg
      51,    // 366: sys_accept4
      990,   // 367: sys_fanotify_init
      1008,  // 368: sys_fanotify_mark
      3847,  // 369: sys_prlimit64
      3316,  // 370: sys_name_to_handle_at
      3467,  // 371: sys_open_by_handle_at
      356,   // 372: sys_clock_adjtime
      6069,  // 373: sys_syncfs
      5109,  // 374: sys_sendmmsg
      5409,  // 375: sys_setns
      3902,  // 376: sys_process_vm_readv
      3923,  // 377: sys_process_vm_writev
      2424,  // 378: sys_kcmp
      1162,  // 379: sys_finit_module
      4891,  // 380: sys_sched_setattr
      4750,  // 381: sys_sched_getattr
      4317,  // 382: sys_renameat2
      4967,  // 383: sys_seccomp
      1859,  // 384: sys_getrandom
      2812,  // 385: sys_memfd_create
      241,   // 386: sys_bpf
      879,   // 387: sys_execveat
      6575,  // 388: sys_userfaultfd
      2797,  // 389: sys_membarrier
      2930,  // 390: sys_mlock2
      617,   // 391: sys_copy_file_range
      3835,  // 392: sys_preadv2
      4046,  // 393: sys_pwritev2
      3748,  // 394: sys_pkey_mprotect
      3719,  // 395: sys_pkey_alloc
      3734,  // 396: sys_pkey_free
      5962,  // 397: sys_statx
      4377,  // 398: sys_rseq
      2226,  // 399: sys_io_pgetevents
      2846,  // 400: sys_migrate_pages
      2433,  // 401: sys_kexec_file_load
      0,     // 402:
      453,   // 403: sys_clock_gettime64
      538,   // 404: sys_clock_settime64
      374,   // 405: sys_clock_adjtime64
      411,   // 406: sys_clock_getres_time64
      493,   // 407: sys_clock_nanosleep_time64
      6226,  // 408: sys_timer_gettime64
      6264,  // 409: sys_timer_settime64
      6335,  // 410: sys_timerfd_gettime64
      6377,  // 411: sys_timerfd_settime64
      6625,  // 412: sys_utimensat_time64
      3978,  // 413: sys_pselect6_time64
      3785,  // 414: sys_ppoll_time64
      0,     // 415:
      2244,  // 416: sys_io_pgetevents_time64
      4224,  // 417: sys_recvmmsg_time64
      3175,  // 418: sys_mq_timedsend_time64
      3131,  // 419: sys_mq_timedreceive_time64
      5050,  // 420: sys_semtimedop_time64
      4515,  // 421: sys_rt_sigtimedwait_time64
      1443,  // 422: sys_futex_time64
      4836,  // 423: sys_sched_rr_get_interval_time64
      3663,  // 424: sys_pidfd_send_signal
      2337,  // 425: sys_io_uring_setup
      2296,  // 426: sys_io_uring_enter
      2315,  // 427: sys_io_uring_register
      3489,  // 428: sys_open_tree
      3016,  // 429: sys_move_mount
      1269,  // 430: sys_fsopen
      1230,  // 431: sys_fsconfig
      1257,  // 432: sys_fsmount
      1280,  // 433: sys_fspick
      3648,  // 434: sys_pidfd_open
      568,   // 435: sys_clone3
      589,   // 436: sys_close_range
      3514,  // 437: sys_openat2
      3632,  // 438: sys_pidfd_getfd
      930,   // 439: sys_faccessat2
      3861,  // 440: sys_process_madvise
      792,   // 441: sys_epoll_pwait2
      2998,  // 442: sys_mount_setattr
      4089,  // 443: sys_quotactl_fd
      2510,  // 444: sys_landlock_create_ruleset
      2488,  // 445: sys_landlock_add_rule
      2538,  // 446: sys_landlock_restrict_self
      0,     // 447:
      3881,  // 448: sys_process_mrelease
      1475,  // 449: sys_futex_waitv
      5163,  // 450: sys_set_mempolicy_home_node
      267,   // 451: sys_cachestat
      1061,  // 452: sys_fchmodat2
      2766,  // 453: sys_map_shadow_stack
      1491,  // 454: sys_futex_wake
      1460,  // 455: sys_futex_wait
      1425,  // 456: sys_futex_requeue
  };
};

struct SyscallTable_x86 {
  static constexpr const char* names = kAllSyscalllNames;
  static constexpr SyscallTable::OffT offsets[]{
      4347,  // 0: sys_restart_syscall
      892,   // 1: sys_exit
      1204,  // 2: sys_fork
      4105,  // 3: sys_read
      6758,  // 4: sys_write
      3458,  // 5: sys_open
      579,   // 6: sys_close
      6746,  // 7: sys_waitpid
      637,   // 8: sys_creat
      2603,  // 9: sys_link
      6528,  // 10: sys_unlink
      868,   // 11: sys_execve
      303,   // 12: sys_chdir
      6144,  // 13: sys_time
      2898,  // 14: sys_mknod
      313,   // 15: sys_chmod
      2565,  // 16: sys_lchown
      249,   // 17: sys_break
      3433,  // 18: sys_oldstat
      2708,  // 19: sys_lseek
      1808,  // 20: sys_getpid
      2988,  // 21: sys_mount
      6495,  // 22: sys_umount
      5620,  // 23: sys_setuid
      2031,  // 24: sys_getuid
      5972,  // 25: sys_stime
      3998,  // 26: sys_ptrace
      124,   // 27: sys_alarm
      3391,  // 28: sys_oldfstat
      3526,  // 29: sys_pause
      6601,  // 30: sys_utime
      5982,  // 31: sys_stty
      2068,  // 32: sys_gtty
      63,    // 33: sys_access
      3382,  // 34: sys_nice
      1375,  // 35: sys_ftime
      6040,  // 36: sys_sync
      2479,  // 37: sys_kill
      4293,  // 38: sys_rename
      2876,  // 39: sys_mkdir
      4367,  // 40: sys_rmdir
      683,   // 41: sys_dup
      3685,  // 42: sys_pipe
      6399,  // 43: sys_times
      3945,  // 44: sys_prof
      259,   // 45: sys_brk
      5325,  // 46: sys_setgid
      1700,  // 47: sys_getgid
      5755,  // 48: sys_signal
      1674,  // 49: sys_geteuid
      1648,  // 50: sys_getegid
      74,    // 51: sys_acct
      6506,  // 52: sys_umount2
      2663,  // 53: sys_lock
      2356,  // 54: sys_ioctl
      1112,  // 55: sys_fcntl
      3059,  // 56: sys_mpx
      5419,  // 57: sys_setpgid
      6474,  // 58: sys_ulimit
      3417,  // 59: sys_oldolduname
      6485,  // 60: sys_umask
      345,   // 61: sys_chroot
      6591,  // 62: sys_ustat
      691,   // 63: sys_dup2
      1831,  // 64: sys_getppid
      1796,  // 65: sys_getpgrp
      5577,  // 66: sys_setsid
      5725,  // 67: sys_sigaction
      5657,  // 68: sys_sgetmask
      5905,  // 69: sys_ssetmask
      5535,  // 70: sys_setreuid
      5447,  // 71: sys_setregid
      5838,  // 72: sys_sigsuspend
      5793,  // 73: sys_sigpending
      5379,  // 74: sys_sethostname
      5563,  // 75: sys_setrlimit
      1933,  // 76: sys_getrlimit
      1947,  // 77: sys_getrusage
      2014,  // 78: sys_gettimeofday
      5603,  // 79: sys_settimeofday
      1724,  // 80: sys_getgroups
      5349,  // 81: sys_setgroups
      4992,  // 82: sys_select
      6014,  // 83: sys_symlink
      3404,  // 84: sys_oldlstat
      4140,  // 85: sys_readlink
      6564,  // 86: sys_uselib
      6003,  // 87: sys_swapon
      4178,  // 88: sys_reboot
      4128,  // 89: sys_readdir
      2954,  // 90: sys_mmap
      3305,  // 91: sys_munmap
      6419,  // 92: sys_truncate
      1385,  // 93: sys_ftruncate
      1037,  // 94: sys_fchmod
      1075,  // 95: sys_fchown
      1843,  // 96: sys_getpriority
      5431,  // 97: sys_setpriority
      3954,  // 98: sys_profil
      5938,  // 99: sys_statfs
      1339,  // 100: sys_fstatfs
      2366,  // 101: sys_ioperm
      5864,  // 102: sys_socketcall
      6114,  // 103: sys_syslog
      5395,  // 104: sys_setitimer
      1754,  // 105: sys_getitimer
      5918,  // 106: sys_stat
      2732,  // 107: sys_lstat
      1291,  // 108: sys_fstat
      3445,  // 109: sys_olduname
      2377,  // 110: sys_iopl
      6667,  // 111: sys_vhangup
      2077,  // 112: sys_idle
      6688,  // 113: sys_vm86old
      6725,  // 114: sys_wait4
      5991,  // 115: sys_swapoff
      6102,  // 116: sys_sysinfo
      2416,  // 117: sys_ipc
      1365,  // 118: sys_fsync
      5824,  // 119: sys_sigreturn
      558,   // 120: sys_clone
      5251,  // 121: sys_setdomainname
      6518,  // 122: sys_uname
      2973,  // 123: sys_modify_ldt
      95,    // 124: sys_adjtimex
      3046,  // 125: sys_mprotect
      5808,  // 126: sys_sigprocmask
      647,   // 127: sys_create_module
      2086,  // 128: sys_init_module
      665,   // 129: sys_delete_module
      1520,  // 130: sys_get_kernel_syms
      4076,  // 131: sys_quotactl
      1784,  // 132: sys_getpgid
      1026,  // 133: sys_fchdir
      220,   // 134: sys_bdflush
      6092,  // 135: sys_sysfs
      3616,  // 136: sys_personality
      108,   // 137: sys_afs_syscall
      5297,  // 138: sys_setfsuid
      5269,  // 139: sys_setfsgid
      1,     // 140: sys__llseek
      1620,  // 141: sys_getdents
      13,    // 142: sys__newselect
      1194,  // 143: sys_flock
      3268,  // 144: sys_msync
      4168,  // 145: sys_readv
      6768,  // 146: sys_writev
      1961,  // 147: sys_getsid
      1134,  // 148: sys_fdatasync
      28,    // 149: sys__sysctl
      2920,  // 150: sys_mlock
      3278,  // 151: sys_munlock
      2941,  // 152: sys_mlockall
      3290,  // 153: sys_munlockall
      4909,  // 154: sys_sched_setparam
      4768,  // 155: sys_sched_getparam
      4928,  // 156: sys_sched_setscheduler
      4787,  // 157: sys_sched_getscheduler
      4951,  // 158: sys_sched_yield
      4674,  // 159: sys_sched_get_priority_max
      4701,  // 160: sys_sched_get_priority_min
      4810,  // 161: sys_sched_rr_get_interval
      3338,  // 162: sys_nanosleep
      3213,  // 163: sys_mremap
      5505,  // 164: sys_setresuid
      1903,  // 165: sys_getresuid
      6679,  // 166: sys_vm86
      4059,  // 167: sys_query_module
      3766,  // 168: sys_poll
      3367,  // 169: sys_nfsservctl
      5475,  // 170: sys_setresgid
      1873,  // 171: sys_getresgid
      3802,  // 172: sys_prctl
      4460,  // 173: sys_rt_sigreturn
      4386,  // 174: sys_rt_sigaction
      4421,  // 175: sys_rt_sigprocmask
      4403,  // 176: sys_rt_sigpending
      4495,  // 177: sys_rt_sigtimedwait
      4440,  // 178: sys_rt_sigqueueinfo
      4477,  // 179: sys_rt_sigsuspend
      3812,  // 180: sys_pread64
      4021,  // 181: sys_pwrite64
      323,   // 182: sys_chown
      1609,  // 183: sys_getcwd
      281,   // 184: sys_capget
      292,   // 185: sys_capset
      5739,  // 186: sys_sigaltstack
      5081,  // 187: sys_sendfile
      1819,  // 188: sys_getpmsg
      4009,  // 189: sys_putpmsg
      6657,  // 190: sys_vfork
      6459,  // 191: sys_ugetrlimit
      2963,  // 192: sys_mmap2
      6432,  // 193: sys_truncate64
      1399,  // 194: sys_ftruncate64
      5927,  // 195: sys_stat64
      2742,  // 196: sys_lstat64
      1301,  // 197: sys_fstat64
      2576,  // 198: sys_lchown32
      2042,  // 199: sys_getuid32
      1711,  // 200: sys_getgid32
      1686,  // 201: sys_geteuid32
      1660,  // 202: sys_getegid32
      5548,  // 203: sys_setreuid32
      5460,  // 204: sys_setregid32
      1738,  // 205: sys_getgroups32
      5363,  // 206: sys_setgroups32
      1086,  // 207: sys_fchown32
      5519,  // 208: sys_setresuid32
      1917,  // 209: sys_getresuid32
      5489,  // 210: sys_setresgid32
      1887,  // 211: sys_getresgid32
      333,   // 212: sys_chown32
      5631,  // 213: sys_setuid32
      5336,  // 214: sys_setgid32
      5310,  // 215: sys_setfsuid32
      5282,  // 216: sys_setfsgid32
      3704,  // 217: sys_pivot_root
      2864,  // 218: sys_mincore
      2754,  // 219: sys_madvise
      1633,  // 220: sys_getdents64
      1122,  // 221: sys_fcntl64
      0,     // 222:
      0,     // 223:
      2003,  // 224: sys_gettid
      4114,  // 225: sys_readahead
      5644,  // 226: sys_setxattr
      2718,  // 227: sys_lsetxattr
      1243,  // 228: sys_fsetxattr
      2055,  // 229: sys_getxattr
      2589,  // 230: sys_lgetxattr
      1148,  // 231: sys_fgetxattr
      2634,  // 232: sys_listxattr
      2648,  // 233: sys_llistxattr
      1179,  // 234: sys_flistxattr
      4277,  // 235: sys_removexattr
      2691,  // 236: sys_lremovexattr
      1213,  // 237: sys_fremovexattr
      6409,  // 238: sys_tkill
      5094,  // 239: sys_sendfile64
      1415,  // 240: sys_futex
      4869,  // 241: sys_sched_setaffinity
      4728,  // 242: sys_sched_getaffinity
      5211,  // 243: sys_set_thread_area
      1578,  // 244: sys_get_thread_area
      2269,  // 245: sys_io_setup
      2194,  // 246: sys_io_destroy
      2209,  // 247: sys_io_getevents
      2282,  // 248: sys_io_submit
      2180,  // 249: sys_io_cancel
      945,   // 250: sys_fadvise64
      0,     // 251:
      901,   // 252: sys_exit_group
      2672,  // 253: sys_lookup_dcookie
      709,   // 254: sys_epoll_create
      744,   // 255: sys_epoll_ctl
      809,   // 256: sys_epoll_wait
      4256,  // 257: sys_remap_file_pages
      5231,  // 258: sys_set_tid_address
      6153,  // 259: sys_timer_create
      6246,  // 260: sys_timer_settime
      6208,  // 261: sys_timer_gettime
      6187,  // 262: sys_timer_getoverrun
      6170,  // 263: sys_timer_delete
      520,   // 264: sys_clock_settime
      435,   // 265: sys_clock_gettime
      394,   // 266: sys_clock_getres
      473,   // 267: sys_clock_nanosleep
      5949,  // 268: sys_statfs64
      1351,  // 269: sys_fstatfs64
      6133,  // 270: sys_tgkill
      6646,  // 271: sys_utimes
      959,   // 272: sys_fadvise64_64
      6713,  // 273: sys_vserver
      2787,  // 274: sys_mbind
      1540,  // 275: sys_get_mempolicy
      5145,  // 276: sys_set_mempolicy
      3099,  // 277: sys_mq_open
      3199,  // 278: sys_mq_unlink
      3158,  // 279: sys_mq_timedsend
      3111,  // 280: sys_mq_timedreceive
      3085,  // 281: sys_mq_notify
      3067,  // 282: sys_mq_getsetattr
      2453,  // 283: sys_kexec_load
      6735,  // 284: sys_waitid
      0,     // 285:
      83,    // 286: sys_add_key
      4331,  // 287: sys_request_key
      2468,  // 288: sys_keyctl
      2401,  // 289: sys_ioprio_set
      2386,  // 290: sys_ioprio_get
      2124,  // 291: sys_inotify_init
      2102,  // 292: sys_inotify_add_watch
      2159,  // 293: sys_inotify_rm_watch
      2846,  // 294: sys_migrate_pages
      3503,  // 295: sys_openat
      2886,  // 296: sys_mkdirat
      2908,  // 297: sys_mknodat
      1099,  // 298: sys_fchownat
      1506,  // 299: sys_futimesat
      1325,  // 300: sys_fstatat64
      6539,  // 301: sys_unlinkat
      4304,  // 302: sys_renameat
      2612,  // 303: sys_linkat
      6026,  // 304: sys_symlinkat
      4153,  // 305: sys_readlinkat
      1048,  // 306: sys_fchmodat
      916,   // 307: sys_faccessat
      3965,  // 308: sys_pselect6
      3775,  // 309: sys_ppoll
      6552,  // 310: sys_unshare
      5191,  // 311: sys_set_robust_list
      1558,  // 312: sys_get_robust_list
      5894,  // 313: sys_splice
      6049,  // 314: sys_sync_file_range
      6125,  // 315: sys_tee
      6700,  // 316: sys_vmsplice
      3031,  // 317: sys_move_pages
      1598,  // 318: sys_getcpu
      776,   // 319: sys_epoll_pwait
      6611,  // 320: sys_utimensat
      5766,  // 321: sys_signalfd
      6296,  // 322: sys_timerfd_create
      843,   // 323: sys_eventfd
      976,   // 324: sys_fallocate
      6357,  // 325: sys_timerfd_settime
      6315,  // 326: sys_timerfd_gettime
      5779,  // 327: sys_signalfd4
      855,   // 328: sys_eventfd2
      726,   // 329: sys_epoll_create1
      700,   // 330: sys_dup3
      3694,  // 331: sys_pipe2
      2141,  // 332: sys_inotify_init1
      3824,  // 333: sys_preadv
      4034,  // 334: sys_pwritev
      4542,  // 335: sys_rt_tgsigqueueinfo
      3596,  // 336: sys_perf_event_open
      4211,  // 337: sys_recvmmsg
      990,   // 338: sys_fanotify_init
      1008,  // 339: sys_fanotify_mark
      3847,  // 340: sys_prlimit64
      3316,  // 341: sys_name_to_handle_at
      3467,  // 342: sys_open_by_handle_at
      356,   // 343: sys_clock_adjtime
      6069,  // 344: sys_syncfs
      5109,  // 345: sys_sendmmsg
      5409,  // 346: sys_setns
      3902,  // 347: sys_process_vm_readv
      3923,  // 348: sys_process_vm_writev
      2424,  // 349: sys_kcmp
      1162,  // 350: sys_finit_module
      4891,  // 351: sys_sched_setattr
      4750,  // 352: sys_sched_getattr
      4317,  // 353: sys_renameat2
      4967,  // 354: sys_seccomp
      1859,  // 355: sys_getrandom
      2812,  // 356: sys_memfd_create
      241,   // 357: sys_bpf
      879,   // 358: sys_execveat
      5853,  // 359: sys_socket
      5879,  // 360: sys_socketpair
      232,   // 361: sys_bind
      605,   // 362: sys_connect
      2623,  // 363: sys_listen
      51,    // 364: sys_accept4
      1988,  // 365: sys_getsockopt
      5588,  // 366: sys_setsockopt
      1972,  // 367: sys_getsockname
      1768,  // 368: sys_getpeername
      5134,  // 369: sys_sendto
      5122,  // 370: sys_sendmsg
      4198,  // 371: sys_recvfrom
      4244,  // 372: sys_recvmsg
      5712,  // 373: sys_shutdown
      6575,  // 374: sys_userfaultfd
      2797,  // 375: sys_membarrier
      2930,  // 376: sys_mlock2
      617,   // 377: sys_copy_file_range
      3835,  // 378: sys_preadv2
      4046,  // 379: sys_pwritev2
      3748,  // 380: sys_pkey_mprotect
      3719,  // 381: sys_pkey_alloc
      3734,  // 382: sys_pkey_free
      5962,  // 383: sys_statx
      134,   // 384: sys_arch_prctl
      2226,  // 385: sys_io_pgetevents
      4377,  // 386: sys_rseq
      0,     // 387:
      0,     // 388:
      0,     // 389:
      0,     // 390:
      0,     // 391:
      0,     // 392:
      5014,  // 393: sys_semget
      5003,  // 394: sys_semctl
      5701,  // 395: sys_shmget
      5680,  // 396: sys_shmctl
      5670,  // 397: sys_shmat
      5691,  // 398: sys_shmdt
      3235,  // 399: sys_msgget
      3257,  // 400: sys_msgsnd
      3246,  // 401: sys_msgrcv
      3224,  // 402: sys_msgctl
      453,   // 403: sys_clock_gettime64
      538,   // 404: sys_clock_settime64
      374,   // 405: sys_clock_adjtime64
      411,   // 406: sys_clock_getres_time64
      493,   // 407: sys_clock_nanosleep_time64
      6226,  // 408: sys_timer_gettime64
      6264,  // 409: sys_timer_settime64
      6335,  // 410: sys_timerfd_gettime64
      6377,  // 411: sys_timerfd_settime64
      6625,  // 412: sys_utimensat_time64
      3978,  // 413: sys_pselect6_time64
      3785,  // 414: sys_ppoll_time64
      0,     // 415:
      2244,  // 416: sys_io_pgetevents_time64
      4224,  // 417: sys_recvmmsg_time64
      3175,  // 418: sys_mq_timedsend_time64
      3131,  // 419: sys_mq_timedreceive_time64
      5050,  // 420: sys_semtimedop_time64
      4515,  // 421: sys_rt_sigtimedwait_time64
      1443,  // 422: sys_futex_time64
      4836,  // 423: sys_sched_rr_get_interval_time64
      3663,  // 424: sys_pidfd_send_signal
      2337,  // 425: sys_io_uring_setup
      2296,  // 426: sys_io_uring_enter
      2315,  // 427: sys_io_uring_register
      3489,  // 428: sys_open_tree
      3016,  // 429: sys_move_mount
      1269,  // 430: sys_fsopen
      1230,  // 431: sys_fsconfig
      1257,  // 432: sys_fsmount
      1280,  // 433: sys_fspick
      3648,  // 434: sys_pidfd_open
      568,   // 435: sys_clone3
      589,   // 436: sys_close_range
      3514,  // 437: sys_openat2
      3632,  // 438: sys_pidfd_getfd
      930,   // 439: sys_faccessat2
      3861,  // 440: sys_process_madvise
      792,   // 441: sys_epoll_pwait2
      2998,  // 442: sys_mount_setattr
      4089,  // 443: sys_quotactl_fd
      2510,  // 444: sys_landlock_create_ruleset
      2488,  // 445: sys_landlock_add_rule
      2538,  // 446: sys_landlock_restrict_self
      2829,  // 447: sys_memfd_secret
      3881,  // 448: sys_process_mrelease
      1475,  // 449: sys_futex_waitv
      5163,  // 450: sys_set_mempolicy_home_node
      267,   // 451: sys_cachestat
      1061,  // 452: sys_fchmodat2
      2766,  // 453: sys_map_shadow_stack
      1491,  // 454: sys_futex_wake
      1460,  // 455: sys_futex_wait
      1425,  // 456: sys_futex_requeue
  };
};

struct SyscallTable_x86_64 {
  static constexpr const char* names = kAllSyscalllNames;
  static constexpr SyscallTable::OffT offsets[]{
      4105,  // 0: sys_read
      6758,  // 1: sys_write
      3458,  // 2: sys_open
      579,   // 3: sys_close
      5918,  // 4: sys_stat
      1291,  // 5: sys_fstat
      2732,  // 6: sys_lstat
      3766,  // 7: sys_poll
      2708,  // 8: sys_lseek
      2954,  // 9: sys_mmap
      3046,  // 10: sys_mprotect
      3305,  // 11: sys_munmap
      259,   // 12: sys_brk
      4386,  // 13: sys_rt_sigaction
      4421,  // 14: sys_rt_sigprocmask
      4460,  // 15: sys_rt_sigreturn
      2356,  // 16: sys_ioctl
      3812,  // 17: sys_pread64
      4021,  // 18: sys_pwrite64
      4168,  // 19: sys_readv
      6768,  // 20: sys_writev
      63,    // 21: sys_access
      3685,  // 22: sys_pipe
      4992,  // 23: sys_select
      4951,  // 24: sys_sched_yield
      3213,  // 25: sys_mremap
      3268,  // 26: sys_msync
      2864,  // 27: sys_mincore
      2754,  // 28: sys_madvise
      5701,  // 29: sys_shmget
      5670,  // 30: sys_shmat
      5680,  // 31: sys_shmctl
      683,   // 32: sys_dup
      691,   // 33: sys_dup2
      3526,  // 34: sys_pause
      3338,  // 35: sys_nanosleep
      1754,  // 36: sys_getitimer
      124,   // 37: sys_alarm
      5395,  // 38: sys_setitimer
      1808,  // 39: sys_getpid
      5081,  // 40: sys_sendfile
      5853,  // 41: sys_socket
      605,   // 42: sys_connect
      40,    // 43: sys_accept
      5134,  // 44: sys_sendto
      4198,  // 45: sys_recvfrom
      5122,  // 46: sys_sendmsg
      4244,  // 47: sys_recvmsg
      5712,  // 48: sys_shutdown
      232,   // 49: sys_bind
      2623,  // 50: sys_listen
      1972,  // 51: sys_getsockname
      1768,  // 52: sys_getpeername
      5879,  // 53: sys_socketpair
      5588,  // 54: sys_setsockopt
      1988,  // 55: sys_getsockopt
      558,   // 56: sys_clone
      1204,  // 57: sys_fork
      6657,  // 58: sys_vfork
      868,   // 59: sys_execve
      892,   // 60: sys_exit
      6725,  // 61: sys_wait4
      2479,  // 62: sys_kill
      6518,  // 63: sys_uname
      5014,  // 64: sys_semget
      5025,  // 65: sys_semop
      5003,  // 66: sys_semctl
      5691,  // 67: sys_shmdt
      3235,  // 68: sys_msgget
      3257,  // 69: sys_msgsnd
      3246,  // 70: sys_msgrcv
      3224,  // 71: sys_msgctl
      1112,  // 72: sys_fcntl
      1194,  // 73: sys_flock
      1365,  // 74: sys_fsync
      1134,  // 75: sys_fdatasync
      6419,  // 76: sys_truncate
      1385,  // 77: sys_ftruncate
      1620,  // 78: sys_getdents
      1609,  // 79: sys_getcwd
      303,   // 80: sys_chdir
      1026,  // 81: sys_fchdir
      4293,  // 82: sys_rename
      2876,  // 83: sys_mkdir
      4367,  // 84: sys_rmdir
      637,   // 85: sys_creat
      2603,  // 86: sys_link
      6528,  // 87: sys_unlink
      6014,  // 88: sys_symlink
      4140,  // 89: sys_readlink
      313,   // 90: sys_chmod
      1037,  // 91: sys_fchmod
      323,   // 92: sys_chown
      1075,  // 93: sys_fchown
      2565,  // 94: sys_lchown
      6485,  // 95: sys_umask
      2014,  // 96: sys_gettimeofday
      1933,  // 97: sys_getrlimit
      1947,  // 98: sys_getrusage
      6102,  // 99: sys_sysinfo
      6399,  // 100: sys_times
      3998,  // 101: sys_ptrace
      2031,  // 102: sys_getuid
      6114,  // 103: sys_syslog
      1700,  // 104: sys_getgid
      5620,  // 105: sys_setuid
      5325,  // 106: sys_setgid
      1674,  // 107: sys_geteuid
      1648,  // 108: sys_getegid
      5419,  // 109: sys_setpgid
      1831,  // 110: sys_getppid
      1796,  // 111: sys_getpgrp
      5577,  // 112: sys_setsid
      5535,  // 113: sys_setreuid
      5447,  // 114: sys_setregid
      1724,  // 115: sys_getgroups
      5349,  // 116: sys_setgroups
      5505,  // 117: sys_setresuid
      1903,  // 118: sys_getresuid
      5475,  // 119: sys_setresgid
      1873,  // 120: sys_getresgid
      1784,  // 121: sys_getpgid
      5297,  // 122: sys_setfsuid
      5269,  // 123: sys_setfsgid
      1961,  // 124: sys_getsid
      281,   // 125: sys_capget
      292,   // 126: sys_capset
      4403,  // 127: sys_rt_sigpending
      4495,  // 128: sys_rt_sigtimedwait
      4440,  // 129: sys_rt_sigqueueinfo
      4477,  // 130: sys_rt_sigsuspend
      5739,  // 131: sys_sigaltstack
      6601,  // 132: sys_utime
      2898,  // 133: sys_mknod
      6564,  // 134: sys_uselib
      3616,  // 135: sys_personality
      6591,  // 136: sys_ustat
      5938,  // 137: sys_statfs
      1339,  // 138: sys_fstatfs
      6092,  // 139: sys_sysfs
      1843,  // 140: sys_getpriority
      5431,  // 141: sys_setpriority
      4909,  // 142: sys_sched_setparam
      4768,  // 143: sys_sched_getparam
      4928,  // 144: sys_sched_setscheduler
      4787,  // 145: sys_sched_getscheduler
      4674,  // 146: sys_sched_get_priority_max
      4701,  // 147: sys_sched_get_priority_min
      4810,  // 148: sys_sched_rr_get_interval
      2920,  // 149: sys_mlock
      3278,  // 150: sys_munlock
      2941,  // 151: sys_mlockall
      3290,  // 152: sys_munlockall
      6667,  // 153: sys_vhangup
      2973,  // 154: sys_modify_ldt
      3704,  // 155: sys_pivot_root
      28,    // 156: sys__sysctl
      3802,  // 157: sys_prctl
      134,   // 158: sys_arch_prctl
      95,    // 159: sys_adjtimex
      5563,  // 160: sys_setrlimit
      345,   // 161: sys_chroot
      6040,  // 162: sys_sync
      74,    // 163: sys_acct
      5603,  // 164: sys_settimeofday
      2988,  // 165: sys_mount
      6506,  // 166: sys_umount2
      6003,  // 167: sys_swapon
      5991,  // 168: sys_swapoff
      4178,  // 169: sys_reboot
      5379,  // 170: sys_sethostname
      5251,  // 171: sys_setdomainname
      2377,  // 172: sys_iopl
      2366,  // 173: sys_ioperm
      647,   // 174: sys_create_module
      2086,  // 175: sys_init_module
      665,   // 176: sys_delete_module
      1520,  // 177: sys_get_kernel_syms
      4059,  // 178: sys_query_module
      4076,  // 179: sys_quotactl
      3367,  // 180: sys_nfsservctl
      1819,  // 181: sys_getpmsg
      4009,  // 182: sys_putpmsg
      108,   // 183: sys_afs_syscall
      6447,  // 184: sys_tuxcall
      4979,  // 185: sys_security
      2003,  // 186: sys_gettid
      4114,  // 187: sys_readahead
      5644,  // 188: sys_setxattr
      2718,  // 189: sys_lsetxattr
      1243,  // 190: sys_fsetxattr
      2055,  // 191: sys_getxattr
      2589,  // 192: sys_lgetxattr
      1148,  // 193: sys_fgetxattr
      2634,  // 194: sys_listxattr
      2648,  // 195: sys_llistxattr
      1179,  // 196: sys_flistxattr
      4277,  // 197: sys_removexattr
      2691,  // 198: sys_lremovexattr
      1213,  // 199: sys_fremovexattr
      6409,  // 200: sys_tkill
      6144,  // 201: sys_time
      1415,  // 202: sys_futex
      4869,  // 203: sys_sched_setaffinity
      4728,  // 204: sys_sched_getaffinity
      5211,  // 205: sys_set_thread_area
      2269,  // 206: sys_io_setup
      2194,  // 207: sys_io_destroy
      2209,  // 208: sys_io_getevents
      2282,  // 209: sys_io_submit
      2180,  // 210: sys_io_cancel
      1578,  // 211: sys_get_thread_area
      2672,  // 212: sys_lookup_dcookie
      709,   // 213: sys_epoll_create
      758,   // 214: sys_epoll_ctl_old
      824,   // 215: sys_epoll_wait_old
      4256,  // 216: sys_remap_file_pages
      1633,  // 217: sys_getdents64
      5231,  // 218: sys_set_tid_address
      4347,  // 219: sys_restart_syscall
      5035,  // 220: sys_semtimedop
      945,   // 221: sys_fadvise64
      6153,  // 222: sys_timer_create
      6246,  // 223: sys_timer_settime
      6208,  // 224: sys_timer_gettime
      6187,  // 225: sys_timer_getoverrun
      6170,  // 226: sys_timer_delete
      520,   // 227: sys_clock_settime
      435,   // 228: sys_clock_gettime
      394,   // 229: sys_clock_getres
      473,   // 230: sys_clock_nanosleep
      901,   // 231: sys_exit_group
      809,   // 232: sys_epoll_wait
      744,   // 233: sys_epoll_ctl
      6133,  // 234: sys_tgkill
      6646,  // 235: sys_utimes
      6713,  // 236: sys_vserver
      2787,  // 237: sys_mbind
      5145,  // 238: sys_set_mempolicy
      1540,  // 239: sys_get_mempolicy
      3099,  // 240: sys_mq_open
      3199,  // 241: sys_mq_unlink
      3158,  // 242: sys_mq_timedsend
      3111,  // 243: sys_mq_timedreceive
      3085,  // 244: sys_mq_notify
      3067,  // 245: sys_mq_getsetattr
      2453,  // 246: sys_kexec_load
      6735,  // 247: sys_waitid
      83,    // 248: sys_add_key
      4331,  // 249: sys_request_key
      2468,  // 250: sys_keyctl
      2401,  // 251: sys_ioprio_set
      2386,  // 252: sys_ioprio_get
      2124,  // 253: sys_inotify_init
      2102,  // 254: sys_inotify_add_watch
      2159,  // 255: sys_inotify_rm_watch
      2846,  // 256: sys_migrate_pages
      3503,  // 257: sys_openat
      2886,  // 258: sys_mkdirat
      2908,  // 259: sys_mknodat
      1099,  // 260: sys_fchownat
      1506,  // 261: sys_futimesat
      3352,  // 262: sys_newfstatat
      6539,  // 263: sys_unlinkat
      4304,  // 264: sys_renameat
      2612,  // 265: sys_linkat
      6026,  // 266: sys_symlinkat
      4153,  // 267: sys_readlinkat
      1048,  // 268: sys_fchmodat
      916,   // 269: sys_faccessat
      3965,  // 270: sys_pselect6
      3775,  // 271: sys_ppoll
      6552,  // 272: sys_unshare
      5191,  // 273: sys_set_robust_list
      1558,  // 274: sys_get_robust_list
      5894,  // 275: sys_splice
      6125,  // 276: sys_tee
      6049,  // 277: sys_sync_file_range
      6700,  // 278: sys_vmsplice
      3031,  // 279: sys_move_pages
      6611,  // 280: sys_utimensat
      776,   // 281: sys_epoll_pwait
      5766,  // 282: sys_signalfd
      6296,  // 283: sys_timerfd_create
      843,   // 284: sys_eventfd
      976,   // 285: sys_fallocate
      6357,  // 286: sys_timerfd_settime
      6315,  // 287: sys_timerfd_gettime
      51,    // 288: sys_accept4
      5779,  // 289: sys_signalfd4
      855,   // 290: sys_eventfd2
      726,   // 291: sys_epoll_create1
      700,   // 292: sys_dup3
      3694,  // 293: sys_pipe2
      2141,  // 294: sys_inotify_init1
      3824,  // 295: sys_preadv
      4034,  // 296: sys_pwritev
      4542,  // 297: sys_rt_tgsigqueueinfo
      3596,  // 298: sys_perf_event_open
      4211,  // 299: sys_recvmmsg
      990,   // 300: sys_fanotify_init
      1008,  // 301: sys_fanotify_mark
      3847,  // 302: sys_prlimit64
      3316,  // 303: sys_name_to_handle_at
      3467,  // 304: sys_open_by_handle_at
      356,   // 305: sys_clock_adjtime
      6069,  // 306: sys_syncfs
      5109,  // 307: sys_sendmmsg
      5409,  // 308: sys_setns
      1598,  // 309: sys_getcpu
      3902,  // 310: sys_process_vm_readv
      3923,  // 311: sys_process_vm_writev
      2424,  // 312: sys_kcmp
      1162,  // 313: sys_finit_module
      4891,  // 314: sys_sched_setattr
      4750,  // 315: sys_sched_getattr
      4317,  // 316: sys_renameat2
      4967,  // 317: sys_seccomp
      1859,  // 318: sys_getrandom
      2812,  // 319: sys_memfd_create
      2433,  // 320: sys_kexec_file_load
      241,   // 321: sys_bpf
      879,   // 322: sys_execveat
      6575,  // 323: sys_userfaultfd
      2797,  // 324: sys_membarrier
      2930,  // 325: sys_mlock2
      617,   // 326: sys_copy_file_range
      3835,  // 327: sys_preadv2
      4046,  // 328: sys_pwritev2
      3748,  // 329: sys_pkey_mprotect
      3719,  // 330: sys_pkey_alloc
      3734,  // 331: sys_pkey_free
      5962,  // 332: sys_statx
      2226,  // 333: sys_io_pgetevents
      4377,  // 334: sys_rseq
      0,     // 335:
      0,     // 336:
      0,     // 337:
      0,     // 338:
      0,     // 339:
      0,     // 340:
      0,     // 341:
      0,     // 342:
      0,     // 343:
      0,     // 344:
      0,     // 345:
      0,     // 346:
      0,     // 347:
      0,     // 348:
      0,     // 349:
      0,     // 350:
      0,     // 351:
      0,     // 352:
      0,     // 353:
      0,     // 354:
      0,     // 355:
      0,     // 356:
      0,     // 357:
      0,     // 358:
      0,     // 359:
      0,     // 360:
      0,     // 361:
      0,     // 362:
      0,     // 363:
      0,     // 364:
      0,     // 365:
      0,     // 366:
      0,     // 367:
      0,     // 368:
      0,     // 369:
      0,     // 370:
      0,     // 371:
      0,     // 372:
      0,     // 373:
      0,     // 374:
      0,     // 375:
      0,     // 376:
      0,     // 377:
      0,     // 378:
      0,     // 379:
      0,     // 380:
      0,     // 381:
      0,     // 382:
      0,     // 383:
      0,     // 384:
      0,     // 385:
      0,     // 386:
      0,     // 387:
      0,     // 388:
      0,     // 389:
      0,     // 390:
      0,     // 391:
      0,     // 392:
      0,     // 393:
      0,     // 394:
      0,     // 395:
      0,     // 396:
      0,     // 397:
      0,     // 398:
      0,     // 399:
      0,     // 400:
      0,     // 401:
      0,     // 402:
      0,     // 403:
      0,     // 404:
      0,     // 405:
      0,     // 406:
      0,     // 407:
      0,     // 408:
      0,     // 409:
      0,     // 410:
      0,     // 411:
      0,     // 412:
      0,     // 413:
      0,     // 414:
      0,     // 415:
      0,     // 416:
      0,     // 417:
      0,     // 418:
      0,     // 419:
      0,     // 420:
      0,     // 421:
      0,     // 422:
      0,     // 423:
      3663,  // 424: sys_pidfd_send_signal
      2337,  // 425: sys_io_uring_setup
      2296,  // 426: sys_io_uring_enter
      2315,  // 427: sys_io_uring_register
      3489,  // 428: sys_open_tree
      3016,  // 429: sys_move_mount
      1269,  // 430: sys_fsopen
      1230,  // 431: sys_fsconfig
      1257,  // 432: sys_fsmount
      1280,  // 433: sys_fspick
      3648,  // 434: sys_pidfd_open
      568,   // 435: sys_clone3
      589,   // 436: sys_close_range
      3514,  // 437: sys_openat2
      3632,  // 438: sys_pidfd_getfd
      930,   // 439: sys_faccessat2
      3861,  // 440: sys_process_madvise
      792,   // 441: sys_epoll_pwait2
      2998,  // 442: sys_mount_setattr
      4089,  // 443: sys_quotactl_fd
      2510,  // 444: sys_landlock_create_ruleset
      2488,  // 445: sys_landlock_add_rule
      2538,  // 446: sys_landlock_restrict_self
      2829,  // 447: sys_memfd_secret
      3881,  // 448: sys_process_mrelease
      1475,  // 449: sys_futex_waitv
      5163,  // 450: sys_set_mempolicy_home_node
      267,   // 451: sys_cachestat
      1061,  // 452: sys_fchmodat2
      2766,  // 453: sys_map_shadow_stack
      1491,  // 454: sys_futex_wake
      1460,  // 455: sys_futex_wait
      1425,  // 456: sys_futex_requeue
      0,     // 457:
      0,     // 458:
      0,     // 459:
      0,     // 460:
      0,     // 461:
      0,     // 462:
      0,     // 463:
      0,     // 464:
      0,     // 465:
      0,     // 466:
      0,     // 467:
      0,     // 468:
      0,     // 469:
      0,     // 470:
      0,     // 471:
      0,     // 472:
      0,     // 473:
      0,     // 474:
      0,     // 475:
      0,     // 476:
      0,     // 477:
      0,     // 478:
      0,     // 479:
      0,     // 480:
      0,     // 481:
      0,     // 482:
      0,     // 483:
      0,     // 484:
      0,     // 485:
      0,     // 486:
      0,     // 487:
      0,     // 488:
      0,     // 489:
      0,     // 490:
      0,     // 491:
      0,     // 492:
      0,     // 493:
      0,     // 494:
      0,     // 495:
      0,     // 496:
      0,     // 497:
      0,     // 498:
      0,     // 499:
      0,     // 500:
      0,     // 501:
      0,     // 502:
      0,     // 503:
      0,     // 504:
      0,     // 505:
      0,     // 506:
      0,     // 507:
      0,     // 508:
      0,     // 509:
      0,     // 510:
      0,     // 511:
      4386,  // 512: sys_rt_sigaction
      4460,  // 513: sys_rt_sigreturn
      2356,  // 514: sys_ioctl
      4168,  // 515: sys_readv
      6768,  // 516: sys_writev
      4198,  // 517: sys_recvfrom
      5122,  // 518: sys_sendmsg
      4244,  // 519: sys_recvmsg
      868,   // 520: sys_execve
      3998,  // 521: sys_ptrace
      4403,  // 522: sys_rt_sigpending
      4495,  // 523: sys_rt_sigtimedwait
      4440,  // 524: sys_rt_sigqueueinfo
      5739,  // 525: sys_sigaltstack
      6153,  // 526: sys_timer_create
      3085,  // 527: sys_mq_notify
      2453,  // 528: sys_kexec_load
      6735,  // 529: sys_waitid
      5191,  // 530: sys_set_robust_list
      1558,  // 531: sys_get_robust_list
      6700,  // 532: sys_vmsplice
      3031,  // 533: sys_move_pages
      3824,  // 534: sys_preadv
      4034,  // 535: sys_pwritev
      4542,  // 536: sys_rt_tgsigqueueinfo
      4211,  // 537: sys_recvmmsg
      5109,  // 538: sys_sendmmsg
      3902,  // 539: sys_process_vm_readv
      3923,  // 540: sys_process_vm_writev
      5588,  // 541: sys_setsockopt
      1988,  // 542: sys_getsockopt
      2269,  // 543: sys_io_setup
      2282,  // 544: sys_io_submit
      879,   // 545: sys_execveat
      3835,  // 546: sys_preadv2
      4046,  // 547: sys_pwritev2
  };
};

struct SyscallTable_s390x {
  static constexpr const char* names = kAllSyscalllNames;
  static constexpr SyscallTable::OffT offsets[]{
      0,     // 0:
      892,   // 1: sys_exit
      1204,  // 2: sys_fork
      4105,  // 3: sys_read
      6758,  // 4: sys_write
      3458,  // 5: sys_open
      579,   // 6: sys_close
      4347,  // 7: sys_restart_syscall
      637,   // 8: sys_creat
      2603,  // 9: sys_link
      6528,  // 10: sys_unlink
      868,   // 11: sys_execve
      303,   // 12: sys_chdir
      0,     // 13:
      2898,  // 14: sys_mknod
      313,   // 15: sys_chmod
      0,     // 16:
      0,     // 17:
      0,     // 18:
      2708,  // 19: sys_lseek
      1808,  // 20: sys_getpid
      2988,  // 21: sys_mount
      6495,  // 22: sys_umount
      0,     // 23:
      0,     // 24:
      0,     // 25:
      3998,  // 26: sys_ptrace
      124,   // 27: sys_alarm
      0,     // 28:
      3526,  // 29: sys_pause
      6601,  // 30: sys_utime
      0,     // 31:
      0,     // 32:
      63,    // 33: sys_access
      3382,  // 34: sys_nice
      0,     // 35:
      6040,  // 36: sys_sync
      2479,  // 37: sys_kill
      4293,  // 38: sys_rename
      2876,  // 39: sys_mkdir
      4367,  // 40: sys_rmdir
      683,   // 41: sys_dup
      3685,  // 42: sys_pipe
      6399,  // 43: sys_times
      0,     // 44:
      259,   // 45: sys_brk
      0,     // 46:
      0,     // 47:
      5755,  // 48: sys_signal
      0,     // 49:
      0,     // 50:
      74,    // 51: sys_acct
      6506,  // 52: sys_umount2
      0,     // 53:
      2356,  // 54: sys_ioctl
      1112,  // 55: sys_fcntl
      0,     // 56:
      5419,  // 57: sys_setpgid
      0,     // 58:
      0,     // 59:
      6485,  // 60: sys_umask
      345,   // 61: sys_chroot
      6591,  // 62: sys_ustat
      691,   // 63: sys_dup2
      1831,  // 64: sys_getppid
      1796,  // 65: sys_getpgrp
      5577,  // 66: sys_setsid
      5725,  // 67: sys_sigaction
      0,     // 68:
      0,     // 69:
      0,     // 70:
      0,     // 71:
      5838,  // 72: sys_sigsuspend
      5793,  // 73: sys_sigpending
      5379,  // 74: sys_sethostname
      5563,  // 75: sys_setrlimit
      0,     // 76:
      1947,  // 77: sys_getrusage
      2014,  // 78: sys_gettimeofday
      5603,  // 79: sys_settimeofday
      0,     // 80:
      0,     // 81:
      0,     // 82:
      6014,  // 83: sys_symlink
      0,     // 84:
      4140,  // 85: sys_readlink
      6564,  // 86: sys_uselib
      6003,  // 87: sys_swapon
      4178,  // 88: sys_reboot
      4128,  // 89: sys_readdir
      2954,  // 90: sys_mmap
      3305,  // 91: sys_munmap
      6419,  // 92: sys_truncate
      1385,  // 93: sys_ftruncate
      1037,  // 94: sys_fchmod
      0,     // 95:
      1843,  // 96: sys_getpriority
      5431,  // 97: sys_setpriority
      0,     // 98:
      5938,  // 99: sys_statfs
      1339,  // 100: sys_fstatfs
      0,     // 101:
      5864,  // 102: sys_socketcall
      6114,  // 103: sys_syslog
      5395,  // 104: sys_setitimer
      1754,  // 105: sys_getitimer
      5918,  // 106: sys_stat
      2732,  // 107: sys_lstat
      1291,  // 108: sys_fstat
      0,     // 109:
      2672,  // 110: sys_lookup_dcookie
      6667,  // 111: sys_vhangup
      2077,  // 112: sys_idle
      0,     // 113:
      6725,  // 114: sys_wait4
      5991,  // 115: sys_swapoff
      6102,  // 116: sys_sysinfo
      2416,  // 117: sys_ipc
      1365,  // 118: sys_fsync
      5824,  // 119: sys_sigreturn
      558,   // 120: sys_clone
      5251,  // 121: sys_setdomainname
      6518,  // 122: sys_uname
      0,     // 123:
      95,    // 124: sys_adjtimex
      3046,  // 125: sys_mprotect
      5808,  // 126: sys_sigprocmask
      647,   // 127: sys_create_module
      2086,  // 128: sys_init_module
      665,   // 129: sys_delete_module
      1520,  // 130: sys_get_kernel_syms
      4076,  // 131: sys_quotactl
      1784,  // 132: sys_getpgid
      1026,  // 133: sys_fchdir
      220,   // 134: sys_bdflush
      6092,  // 135: sys_sysfs
      3616,  // 136: sys_personality
      108,   // 137: sys_afs_syscall
      0,     // 138:
      0,     // 139:
      0,     // 140:
      1620,  // 141: sys_getdents
      4992,  // 142: sys_select
      1194,  // 143: sys_flock
      3268,  // 144: sys_msync
      4168,  // 145: sys_readv
      6768,  // 146: sys_writev
      1961,  // 147: sys_getsid
      1134,  // 148: sys_fdatasync
      28,    // 149: sys__sysctl
      2920,  // 150: sys_mlock
      3278,  // 151: sys_munlock
      2941,  // 152: sys_mlockall
      3290,  // 153: sys_munlockall
      4909,  // 154: sys_sched_setparam
      4768,  // 155: sys_sched_getparam
      4928,  // 156: sys_sched_setscheduler
      4787,  // 157: sys_sched_getscheduler
      4951,  // 158: sys_sched_yield
      4674,  // 159: sys_sched_get_priority_max
      4701,  // 160: sys_sched_get_priority_min
      4810,  // 161: sys_sched_rr_get_interval
      3338,  // 162: sys_nanosleep
      3213,  // 163: sys_mremap
      0,     // 164:
      0,     // 165:
      0,     // 166:
      4059,  // 167: sys_query_module
      3766,  // 168: sys_poll
      3367,  // 169: sys_nfsservctl
      0,     // 170:
      0,     // 171:
      3802,  // 172: sys_prctl
      4460,  // 173: sys_rt_sigreturn
      4386,  // 174: sys_rt_sigaction
      4421,  // 175: sys_rt_sigprocmask
      4403,  // 176: sys_rt_sigpending
      4495,  // 177: sys_rt_sigtimedwait
      4440,  // 178: sys_rt_sigqueueinfo
      4477,  // 179: sys_rt_sigsuspend
      3812,  // 180: sys_pread64
      4021,  // 181: sys_pwrite64
      0,     // 182:
      1609,  // 183: sys_getcwd
      281,   // 184: sys_capget
      292,   // 185: sys_capset
      5739,  // 186: sys_sigaltstack
      5081,  // 187: sys_sendfile
      1819,  // 188: sys_getpmsg
      4009,  // 189: sys_putpmsg
      6657,  // 190: sys_vfork
      1933,  // 191: sys_getrlimit
      0,     // 192:
      0,     // 193:
      0,     // 194:
      0,     // 195:
      0,     // 196:
      0,     // 197:
      2565,  // 198: sys_lchown
      2031,  // 199: sys_getuid
      1700,  // 200: sys_getgid
      1674,  // 201: sys_geteuid
      1648,  // 202: sys_getegid
      5535,  // 203: sys_setreuid
      5447,  // 204: sys_setregid
      1724,  // 205: sys_getgroups
      5349,  // 206: sys_setgroups
      1075,  // 207: sys_fchown
      5505,  // 208: sys_setresuid
      1903,  // 209: sys_getresuid
      5475,  // 210: sys_setresgid
      1873,  // 211: sys_getresgid
      323,   // 212: sys_chown
      5620,  // 213: sys_setuid
      5325,  // 214: sys_setgid
      5297,  // 215: sys_setfsuid
      5269,  // 216: sys_setfsgid
      3704,  // 217: sys_pivot_root
      2864,  // 218: sys_mincore
      2754,  // 219: sys_madvise
      1633,  // 220: sys_getdents64
      0,     // 221:
      4114,  // 222: sys_readahead
      0,     // 223:
      5644,  // 224: sys_setxattr
      2718,  // 225: sys_lsetxattr
      1243,  // 226: sys_fsetxattr
      2055,  // 227: sys_getxattr
      2589,  // 228: sys_lgetxattr
      1148,  // 229: sys_fgetxattr
      2634,  // 230: sys_listxattr
      2648,  // 231: sys_llistxattr
      1179,  // 232: sys_flistxattr
      4277,  // 233: sys_removexattr
      2691,  // 234: sys_lremovexattr
      1213,  // 235: sys_fremovexattr
      2003,  // 236: sys_gettid
      6409,  // 237: sys_tkill
      1415,  // 238: sys_futex
      4869,  // 239: sys_sched_setaffinity
      4728,  // 240: sys_sched_getaffinity
      6133,  // 241: sys_tgkill
      0,     // 242:
      2269,  // 243: sys_io_setup
      2194,  // 244: sys_io_destroy
      2209,  // 245: sys_io_getevents
      2282,  // 246: sys_io_submit
      2180,  // 247: sys_io_cancel
      901,   // 248: sys_exit_group
      709,   // 249: sys_epoll_create
      744,   // 250: sys_epoll_ctl
      809,   // 251: sys_epoll_wait
      5231,  // 252: sys_set_tid_address
      945,   // 253: sys_fadvise64
      6153,  // 254: sys_timer_create
      6246,  // 255: sys_timer_settime
      6208,  // 256: sys_timer_gettime
      6187,  // 257: sys_timer_getoverrun
      6170,  // 258: sys_timer_delete
      520,   // 259: sys_clock_settime
      435,   // 260: sys_clock_gettime
      394,   // 261: sys_clock_getres
      473,   // 262: sys_clock_nanosleep
      0,     // 263:
      0,     // 264:
      5949,  // 265: sys_statfs64
      1351,  // 266: sys_fstatfs64
      4256,  // 267: sys_remap_file_pages
      2787,  // 268: sys_mbind
      1540,  // 269: sys_get_mempolicy
      5145,  // 270: sys_set_mempolicy
      3099,  // 271: sys_mq_open
      3199,  // 272: sys_mq_unlink
      3158,  // 273: sys_mq_timedsend
      3111,  // 274: sys_mq_timedreceive
      3085,  // 275: sys_mq_notify
      3067,  // 276: sys_mq_getsetattr
      2453,  // 277: sys_kexec_load
      83,    // 278: sys_add_key
      4331,  // 279: sys_request_key
      2468,  // 280: sys_keyctl
      6735,  // 281: sys_waitid
      2401,  // 282: sys_ioprio_set
      2386,  // 283: sys_ioprio_get
      2124,  // 284: sys_inotify_init
      2102,  // 285: sys_inotify_add_watch
      2159,  // 286: sys_inotify_rm_watch
      2846,  // 287: sys_migrate_pages
      3503,  // 288: sys_openat
      2886,  // 289: sys_mkdirat
      2908,  // 290: sys_mknodat
      1099,  // 291: sys_fchownat
      1506,  // 292: sys_futimesat
      3352,  // 293: sys_newfstatat
      6539,  // 294: sys_unlinkat
      4304,  // 295: sys_renameat
      2612,  // 296: sys_linkat
      6026,  // 297: sys_symlinkat
      4153,  // 298: sys_readlinkat
      1048,  // 299: sys_fchmodat
      916,   // 300: sys_faccessat
      3965,  // 301: sys_pselect6
      3775,  // 302: sys_ppoll
      6552,  // 303: sys_unshare
      5191,  // 304: sys_set_robust_list
      1558,  // 305: sys_get_robust_list
      5894,  // 306: sys_splice
      6049,  // 307: sys_sync_file_range
      6125,  // 308: sys_tee
      6700,  // 309: sys_vmsplice
      3031,  // 310: sys_move_pages
      1598,  // 311: sys_getcpu
      776,   // 312: sys_epoll_pwait
      6646,  // 313: sys_utimes
      976,   // 314: sys_fallocate
      6611,  // 315: sys_utimensat
      5766,  // 316: sys_signalfd
      6284,  // 317: sys_timerfd
      843,   // 318: sys_eventfd
      6296,  // 319: sys_timerfd_create
      6357,  // 320: sys_timerfd_settime
      6315,  // 321: sys_timerfd_gettime
      5779,  // 322: sys_signalfd4
      855,   // 323: sys_eventfd2
      2141,  // 324: sys_inotify_init1
      3694,  // 325: sys_pipe2
      700,   // 326: sys_dup3
      726,   // 327: sys_epoll_create1
      3824,  // 328: sys_preadv
      4034,  // 329: sys_pwritev
      4542,  // 330: sys_rt_tgsigqueueinfo
      3596,  // 331: sys_perf_event_open
      990,   // 332: sys_fanotify_init
      1008,  // 333: sys_fanotify_mark
      3847,  // 334: sys_prlimit64
      3316,  // 335: sys_name_to_handle_at
      3467,  // 336: sys_open_by_handle_at
      356,   // 337: sys_clock_adjtime
      6069,  // 338: sys_syncfs
      5409,  // 339: sys_setns
      3902,  // 340: sys_process_vm_readv
      3923,  // 341: sys_process_vm_writev
      4636,  // 342: sys_s390_runtime_instr
      2424,  // 343: sys_kcmp
      1162,  // 344: sys_finit_module
      4891,  // 345: sys_sched_setattr
      4750,  // 346: sys_sched_getattr
      4317,  // 347: sys_renameat2
      4967,  // 348: sys_seccomp
      1859,  // 349: sys_getrandom
      2812,  // 350: sys_memfd_create
      241,   // 351: sys_bpf
      4612,  // 352: sys_s390_pci_mmio_write
      4589,  // 353: sys_s390_pci_mmio_read
      879,   // 354: sys_execveat
      6575,  // 355: sys_userfaultfd
      2797,  // 356: sys_membarrier
      4211,  // 357: sys_recvmmsg
      5109,  // 358: sys_sendmmsg
      5853,  // 359: sys_socket
      5879,  // 360: sys_socketpair
      232,   // 361: sys_bind
      605,   // 362: sys_connect
      2623,  // 363: sys_listen
      51,    // 364: sys_accept4
      1988,  // 365: sys_getsockopt
      5588,  // 366: sys_setsockopt
      1972,  // 367: sys_getsockname
      1768,  // 368: sys_getpeername
      5134,  // 369: sys_sendto
      5122,  // 370: sys_sendmsg
      4198,  // 371: sys_recvfrom
      4244,  // 372: sys_recvmsg
      5712,  // 373: sys_shutdown
      2930,  // 374: sys_mlock2
      617,   // 375: sys_copy_file_range
      3835,  // 376: sys_preadv2
      4046,  // 377: sys_pwritev2
      4564,  // 378: sys_s390_guarded_storage
      5962,  // 379: sys_statx
      4659,  // 380: sys_s390_sthyi
      2433,  // 381: sys_kexec_file_load
      2226,  // 382: sys_io_pgetevents
      4377,  // 383: sys_rseq
      3748,  // 384: sys_pkey_mprotect
      3719,  // 385: sys_pkey_alloc
      3734,  // 386: sys_pkey_free
      0,     // 387:
      0,     // 388:
      0,     // 389:
      0,     // 390:
      0,     // 391:
      5035,  // 392: sys_semtimedop
      5014,  // 393: sys_semget
      5003,  // 394: sys_semctl
      5701,  // 395: sys_shmget
      5680,  // 396: sys_shmctl
      5670,  // 397: sys_shmat
      5691,  // 398: sys_shmdt
      3235,  // 399: sys_msgget
      3257,  // 400: sys_msgsnd
      3246,  // 401: sys_msgrcv
      3224,  // 402: sys_msgctl
      0,     // 403:
      0,     // 404:
      0,     // 405:
      0,     // 406:
      0,     // 407:
      0,     // 408:
      0,     // 409:
      0,     // 410:
      0,     // 411:
      0,     // 412:
      0,     // 413:
      0,     // 414:
      0,     // 415:
      0,     // 416:
      0,     // 417:
      0,     // 418:
      0,     // 419:
      0,     // 420:
      0,     // 421:
      0,     // 422:
      0,     // 423:
      3663,  // 424: sys_pidfd_send_signal
      2337,  // 425: sys_io_uring_setup
      2296,  // 426: sys_io_uring_enter
      2315,  // 427: sys_io_uring_register
      3489,  // 428: sys_open_tree
      3016,  // 429: sys_move_mount
      1269,  // 430: sys_fsopen
      1230,  // 431: sys_fsconfig
      1257,  // 432: sys_fsmount
      1280,  // 433: sys_fspick
      3648,  // 434: sys_pidfd_open
      568,   // 435: sys_clone3
      589,   // 436: sys_close_range
      3514,  // 437: sys_openat2
      3632,  // 438: sys_pidfd_getfd
      930,   // 439: sys_faccessat2
      3861,  // 440: sys_process_madvise
      792,   // 441: sys_epoll_pwait2
      2998,  // 442: sys_mount_setattr
      4089,  // 443: sys_quotactl_fd
      2510,  // 444: sys_landlock_create_ruleset
      2488,  // 445: sys_landlock_add_rule
      2538,  // 446: sys_landlock_restrict_self
      0,     // 447:
      3881,  // 448: sys_process_mrelease
      1475,  // 449: sys_futex_waitv
      5163,  // 450: sys_set_mempolicy_home_node
  };
};

}  // namespace perfetto
#endif  // SRC_KERNEL_UTILS_SYSCALL_TABLE_GENERATED_H_
